/**
 * `agent.sh` — the agent's own Quimby coordination tool. It is the *mechanical enactment* layer
 * under the CLAUDE.md conventions: the conventions keep every judgment call (whether/when to
 * send, what to record where, how to weigh a peer note), and this tool performs the fiddly,
 * silent-failure-prone steps reliably — the atomic author-then-publish move, the exact
 * `quimby-attest` block, the inbox `received → processed` lifecycle.
 *
 * It is a POSIX **shell** script, not a Node program, on purpose: it runs *inside* the
 * sandbox/remote, where quimby's guaranteed floor is `sh` + `git` + coreutils (git is already a
 * hard remote dependency) but Node is **not** — an Ollama/qwen runtime may have no Node, and the
 * whole point of cheap agents is that they work there. A shell tool adds zero new remote
 * dependency. DRY is preserved where it is fragile: the host is always the *parser* of these
 * formats (canonical TypeScript), the agent is only ever the *producer*, so there is no
 * duplicated parser to drift — only a producer/consumer contract, pinned by a round-trip test.
 *
 * The tool never crosses the boundary: carrying a parcel to a peer, or out to the user's repo,
 * stays the host's job (`quimby dispatch`/`merge`). `agent.sh` only ever writes the agent's
 * own workspace. And it is an *optimization* over the prose conventions, never a replacement — a
 * runtime without `sh` (or any agent lacking the script) still works by following CLAUDE.md.
 */
export const AGENT_SCRIPT_CMD_FILENAME = 'agent.cmd'

export const AGENT_SCRIPT_LEGACY_CMD_FILENAME = 'quimby-agent.cmd'

export const AGENT_SCRIPT_LEGACY_SH_FILENAME = 'quimby-agent.sh'

export const AGENT_SCRIPT_SH_FILENAME = 'agent.sh'

/**
 * The coordination graph baked into the generated tool, resolved by the caller (which holds the
 * state) exactly like the `{{coordination}}` clause in the agent's instructions.
 */
export interface AgentScriptGraph {
  /** Every OTHER current agent — who this one may address at all. */
  roster?: readonly string[]
  /** Who this one may escalate to, already `@role`-expanded. */
  escalatesTo?: readonly string[]
  /** Who this one may direct. */
  directs?: readonly string[]
  /** Who may direct THIS one — the inbound edge, which it cannot derive from anything it sees. */
  directedBy?: readonly string[]
}

/**
 * The POSIX `sh` implementation — the canonical one, since every place `quimby-agent` actually
 * runs (Docker Sandbox, OpenShell, SSH to Linux/macOS) is POSIX. Deps: `sh` + `git` + coreutils.
 */
export function renderAgentScript(graph: Readonly<AgentScriptGraph> = {}): string {
  return applyGraph(SH_LINES.join('\n') + '\n', graph)
}

/**
 * The Windows `cmd` twin, for the one place `sh` is absent: a Windows-hosted local agent. Remote
 * sandboxes are POSIX, so this is a best-effort safety net — see {@link renderAgentScript} for the
 * canonical behavior. If it misbehaves, the CLAUDE.md prose conventions are the fallback. Deps:
 * `cmd` + `git`.
 */
export function renderAgentScriptCmd(graph: Readonly<AgentScriptGraph> = {}): string {
  return applyGraph(CMD_LINES.join('\r\n') + '\r\n', graph)
}

// Substitute the resolved graph into the rendered script. Names are roster-validated upstream
// (`[A-Za-z0-9_-]`), but this filters anyway: a name carrying a quote or space would otherwise
// break out of the single-quoted shell assignment it lands in.
function applyGraph(script: string, graph: Readonly<AgentScriptGraph>): string {
  // `roster` is what every caller resolves (via resolveAgentGraph), so its presence — not its
  // emptiness — is the signal that a graph was rendered. A lone agent legitimately has an empty
  // roster and must still refuse every recipient.
  return script
    .replaceAll('{{graph}}', graph.roster === undefined ? '' : '1')
    .replaceAll('{{roster}}', safeNames(graph.roster))
    .replaceAll('{{escalate}}', safeNames(graph.escalatesTo))
    .replaceAll('{{directs}}', safeNames(graph.directs))
    .replaceAll('{{directedby}}', safeNames(graph.directedBy))
}

function safeNames(names: readonly string[] | undefined): string {
  return (names ?? []).filter((name) => /^[A-Za-z0-9_-]+$/.test(name)).join(' ')
}

// Each line is a JS double-quoted string: sh `"` is escaped `\"`, sh `\` is escaped `\\` (so a
// shell `\n` reads as backslash-n for printf), backticks are literal. No `${...}` is used in the
// shell (guards replace parameter defaults), so nothing here interpolates.
const SH_LINES = [
  '#!/bin/sh',
  "# agent.sh — the agent's Quimby coordination tool: mechanical enactment of the assignment /",
  '# status / handoff / inbox / attest conventions. Judgment (whether/when to send, what to record) stays in CLAUDE.md; this',
  "# only performs the error-prone steps reliably. Deps: sh + git + coreutils (quimby's guaranteed",
  '# remote floor) — no node. If this tool is absent, the CLAUDE.md conventions are the fallback.',
  "# Carrying across the boundary is the host's job; this only ever writes your own workspace.",
  'set -eu',
  '',
  'qa_die() { echo "agent.sh: $1" >&2; exit 1; }',
  '',
  '# The coordination graph, resolved by the host and baked in here — refreshed on every launch and',
  '# every `quimby sync`, exactly like the CLAUDE.md coordination clause. Without it this tool could',
  '# only check that a recipient is non-empty, so addressing a removed agent published happily and',
  '# then bounced host-side, where the sender never sees it: the parcel sits in out/queued forever',
  '# and (bounces being attempt-once) stops even warning. Checking here is the only place the sender',
  '# learns. QA_ROSTER = every other current agent; QA_ESCALATE = who this one may summon.',
  '# QA_GRAPH marks that a graph was rendered AT ALL. Without it an empty QA_ESCALATE is ambiguous',
  '# — "the host told us nothing" (an old or ungraphed script, where blocking would be wrong) versus',
  '# "you genuinely have no escalation target" (where saying so is the whole point). Every check',
  '# below is gated on it, so a tool rendered without a graph behaves exactly as it did before.',
  "QA_GRAPH='{{graph}}'",
  "QA_ROSTER='{{roster}}'",
  "QA_ESCALATE='{{escalate}}'",
  "QA_DIRECTS='{{directs}}'",
  "QA_DIRECTED_BY='{{directedby}}'",
  '',
  '# Is $1 in the space-separated list $2? Callers gate on QA_GRAPH first, so reaching here with an',
  '# empty list means the host really said "nobody" — which must MISS, not pass.',
  'qa_in_list() {',
  '  [ -n "$2" ] || return 1',
  '  for qa_n in $2; do',
  '    [ "$qa_n" = "$1" ] && return 0',
  '  done',
  '  return 1',
  '}',
  '',
  '# mkdir -p, but on failure name the most likely cause. A host-side `quimby rebuild` replaces',
  '# handoff/{in,out} under the guest mount, and a virtiofs/9p guest can keep a stale dentry: the',
  '# dir still lists (getdents) but stat returns ENOENT, so mkdir -p of a child fails. Dropping the',
  '# guest cache needs root, so this cannot self-heal — it points at the fix instead of dying blind.',
  'qa_mkdir() {',
  '  mkdir -p "$1" 2>/dev/null && return 0',
  '  echo "agent.sh: could not create \'$1\'." >&2',
  '  echo "agent.sh: if handoff/ lists but its entries stat as \'?\' or ENOENT, the guest is holding a" >&2',
  '  echo "  stale virtiofs dentry (common right after a host-side \'quimby rebuild\'). Drop it and retry:" >&2',
  '  echo "    sync; echo 2 | sudo tee /proc/sys/vm/drop_caches" >&2',
  '  exit 1',
  '}',
  '',
  '# Close the guest bind-mount cache-lag window (same virtiofs/9p class as qa_mkdir): a courier',
  '# nudge naming a parcel can arrive before the just-delivered parcel is visible on this side, so',
  '# poll for the dir a few times before declaring it truly missing. QA_INBOX_RETRIES tunes the count',
  '# (default 3 ≈ 2s of 1s sleeps); the transient-vs-loss line is drawn at the retry boundary.',
  'qa_await_dir() {',
  '  set +u; tries=$QA_INBOX_RETRIES; set -u',
  '  [ -n "$tries" ] || tries=3',
  '  i=1',
  '  while :; do',
  '    [ -d "$1" ] && return 0',
  '    [ "$i" -ge "$tries" ] && return 1',
  '    i=$((i + 1))',
  '    sleep 1',
  '  done',
  '}',
  '',
  '# Record that this agent has ENGAGED with a parcel — read it, or deliberately closed it by name.',
  '# Two things read this ledger, and both are asking the same question: has anyone actually dealt',
  "# with this? `inbox done --all` closes only what is listed here, and the host's mailbox GC keeps",
  '# a processed parcel that is NOT listed rather than sweeping it, because a parcel nobody opened',
  '# is unread work, not cache.',
  'qa_mark_opened() {',
  '  grep -qxF "$1" "$ROOT/handoff/in/.opened" 2>/dev/null ||',
  '    printf \'%s\\n\' "$1" >> "$ROOT/handoff/in/.opened"',
  '}',
  '',
  '# The agent root is the nearest ancestor holding both handoff/ and assignment.md (present at the',
  '# agent root, never inside repo/), so the tool works from the agent dir or from within repo/.',
  'qa_root() {',
  '  d=$PWD',
  '  while [ "$d" != "/" ]; do',
  '    if [ -d "$d/handoff" ] && [ -f "$d/assignment.md" ]; then',
  '      printf \'%s\\n\' "$d"',
  '      return 0',
  '    fi',
  '    d=$(dirname "$d")',
  '  done',
  '  return 1',
  '}',
  '',
  '# Publish is the atomic author-then-publish move: a same-filesystem rename of the whole draft',
  '# dir into out/queued/, so a partial parcel never appears as queued (the race fix by construction).',
  "# What the parcel actually CARRIES, as arithmetic rather than the sender's diligence. A parcel",
  '# is cumulative since quimby/seed, so an agent that believes it is handing over one commit can',
  '# hand over six — the other five being work that already landed. One of those can silently revert',
  '# a closed decision: it merges without a conflict, so nothing downstream flags it. The tool',
  '# already knows the range it captures, so saying it costs nothing and hands over the discrepancy.',
  'qa_carry_summary() {',
  '  qa_repo="$ROOT/repo"',
  '  [ -d "$qa_repo" ] || return 0',
  '  git -C "$qa_repo" rev-parse -q --verify quimby/seed >/dev/null 2>&1 || return 0',
  '  qa_commits=$(git -C "$qa_repo" rev-list --count quimby/seed..HEAD 2>/dev/null || echo 0)',
  '  qa_files=$(git -C "$qa_repo" status --porcelain 2>/dev/null | wc -l | tr -d " ")',
  '  if [ "$qa_commits" -gt 0 ]; then',
  '    qa_from=$(git -C "$qa_repo" rev-parse --short quimby/seed 2>/dev/null)',
  '    qa_to=$(git -C "$qa_repo" rev-parse --short HEAD 2>/dev/null)',
  '    echo "          carrying $qa_commits commit(s) ($qa_from..$qa_to) + $qa_files uncommitted file(s)"',
  '  else',
  '    echo "          carrying 0 commits + $qa_files uncommitted file(s)"',
  '  fi',
  '  # The stale-seed case is WHY the count surprises people, so diagnose it here rather than',
  '  # leaving the sender to work out why six commits appeared. A seed behind the delivered base',
  '  # means everything peers landed since it is still inside seed..HEAD and rides along again.',
  '  git -C "$qa_repo" rev-parse -q --verify quimby/base >/dev/null 2>&1 || return 0',
  '  qa_behind=$(git -C "$qa_repo" rev-list --count quimby/seed..quimby/base 2>/dev/null || echo 0)',
  '  [ "$qa_behind" -gt 0 ] || return 0',
  '  echo "          NOTE your seed is $qa_behind commit(s) behind quimby/base, so this carry re-includes"',
  '  echo "          work that already landed. ./agent.sh rebase first unless you meant that."',
  '}',
  '',
  'qa_publish() {',
  '  recipient=$1',
  '  draft="$ROOT/handoff/out/draft/$recipient"',
  '  [ -d "$draft" ] || qa_die "publish: no draft for \'$recipient\'"',
  '  qa_mkdir "$ROOT/handoff/out/queued"',
  '  queued="$ROOT/handoff/out/queued/$recipient"',
  '  rm -rf "$queued"',
  '  mv "$draft" "$queued"',
  '  # Name what the parcel CONTAINS, not just that it was queued. Agents were sending a note and',
  '  # then reaching for a second step to send their commits — because nothing here said the note',
  '  # and the work travel together. One parcel, one move; there is no separate verb for the code.',
  '  echo "agent.sh: queued parcel for \'$recipient\' — carries your note AND your work (everything in"',
  '  echo "          repo/ since quimby/seed: commits + uncommitted). One parcel; nothing else to send."',
  '  qa_carry_summary',
  '  echo "          quimby dispatch carries it (the server also auto-dispatches)."',
  '}',
  '',
  'qa_read_stdin() {',
  '  tmp=$(mktemp)',
  '  cat > "$tmp"',
  '  printf \'%s\\n\' "$tmp"',
  '}',
  '',
  'cmd_assignment() {',
  '  if [ $# -gt 0 ]; then sub=$1; shift; else sub=show; fi',
  '  case $sub in',
  '    show)',
  '      cat "$ROOT/assignment.md"',
  '      ;;',
  '    set)',
  "      message=''",
  "      file=''",
  '      while [ $# -gt 0 ]; do',
  '        case $1 in',
  '          -m|--message) shift; [ $# -gt 0 ] || qa_die "assignment set: -m needs text"; message=$1 ;;',
  '          --file) shift; [ $# -gt 0 ] || qa_die "assignment set: --file needs a path"; file=$1 ;;',
  '          -*) qa_die "assignment set: unknown option $1" ;;',
  '          *) qa_die "assignment set: unexpected arg $1" ;;',
  '        esac',
  '        shift',
  '      done',
  '      if [ -n "$file" ]; then',
  '        [ "$file" = "-" ] || [ -f "$file" ] || qa_die "assignment set: --file not found: $file"',
  '        if [ "$file" = "-" ]; then tmp=$(qa_read_stdin); mv "$tmp" "$ROOT/assignment.md"; else cp "$file" "$ROOT/assignment.md"; fi',
  '      else',
  '        [ -n "$message" ] || qa_die "assignment set: provide -m or --file"',
  '        printf \'%s\\n\' "$message" > "$ROOT/assignment.md"',
  '      fi',
  '      echo "agent.sh: assignment set"',
  '      ;;',
  '    *) qa_die "assignment: unknown subcommand \'$sub\' (show | set -m text | set --file path)" ;;',
  '  esac',
  '}',
  '',
  'cmd_status() {',
  '  if [ $# -gt 0 ]; then sub=$1; shift; else sub=show; fi',
  '  case $sub in',
  '    show)',
  '      cat "$ROOT/status.md"',
  '      ;;',
  '    set|append|done)',
  "      message=''",
  "      file=''",
  '      while [ $# -gt 0 ]; do',
  '        case $1 in',
  '          -m|--message) shift; [ $# -gt 0 ] || qa_die "status $sub: -m needs text"; message=$1 ;;',
  '          --file) shift; [ $# -gt 0 ] || qa_die "status $sub: --file needs a path"; file=$1 ;;',
  '          -*) qa_die "status $sub: unknown option $1" ;;',
  '          *) qa_die "status $sub: unexpected arg $1" ;;',
  '        esac',
  '        shift',
  '      done',
  '      if [ "$sub" = done ] && [ -z "$message" ] && [ -z "$file" ]; then message=done.; fi',
  '      if [ -n "$file" ]; then',
  '        [ "$file" = "-" ] || [ -f "$file" ] || qa_die "status $sub: --file not found: $file"',
  '        if [ "$file" = "-" ]; then src=$(qa_read_stdin); else src=$file; fi',
  '        if [ "$sub" = set ]; then cp "$src" "$ROOT/status.md"; else cat "$src" >> "$ROOT/status.md"; fi',
  '        [ "$file" = "-" ] && rm -f "$src"',
  '      else',
  '        [ -n "$message" ] || qa_die "status $sub: provide -m or --file"',
  '        if [ "$sub" = set ]; then printf \'%s\\n\' "$message" > "$ROOT/status.md"; else printf \'\\n%s\\n\' "$message" >> "$ROOT/status.md"; fi',
  '      fi',
  '      echo "agent.sh: status $sub"',
  '      # `append` is the easy path and `set` the effortful one, so a status journal only ever',
  '      # grows — and its whole job is to be the ONE thing a successor reads after a reset. Past a',
  '      # few thousand words that successor reads history to find the present, and superseded',
  '      # present-tense claims sit there looking current. A warning, never a refusal: what belongs',
  '      # in it is judgment, and this tool only does mechanics.',
  '      qa_bytes=$(wc -c < "$ROOT/status.md" 2>/dev/null || echo 0)',
  '      if [ "$qa_bytes" -gt 16000 ]; then',
  '        printf \'agent.sh: status.md is %s bytes — long enough that a successor reads history\\n\' "$qa_bytes" >&2',
  '        echo "          to find the present. Rewrite it with \'status set\' (current state, open" >&2',
  '        echo "          threads, next step); append within an arc, rewrite at the end of one." >&2',
  '      fi',
  '      ;;',
  '    *) qa_die "status: unknown subcommand \'$sub\' (show | set | append | done)" ;;',
  '  esac',
  '}',
  '',
  'cmd_handoff() {',
  '  mode=$1',
  '  shift',
  "  recipient=''",
  "  message=''",
  "  attach=''",
  "  replyto=''",
  '  publish=1',
  "  files=''",
  '  while [ $# -gt 0 ]; do',
  '    case $1 in',
  '      -m|--message) shift; [ $# -gt 0 ] || qa_die "handoff: -m needs a message"; message=$1 ;;',
  '      --attach) shift; [ $# -gt 0 ] || qa_die "handoff: --attach needs an agent"; attach=$1 ;;',
  '      --to) shift; [ $# -gt 0 ] || qa_die "reply: --to needs a parcel name"; replyto=$1 ;;',
  '      --file) shift; [ $# -gt 0 ] || qa_die "handoff: --file needs a path"; files="$files $1" ;;',
  '      # The note BODY from a file, which `--file` deliberately does not do — it attaches. That',
  '      # asymmetry with `status set --file` (where the file IS the content) sent real parcels out',
  '      # with empty notes, so the body has its own flag rather than an overloaded one.',
  '      --note-file)',
  '        shift',
  '        [ $# -gt 0 ] || qa_die "handoff: --note-file needs a path"',
  '        if [ "$1" = "-" ]; then',
  '          qa_nf=$(qa_read_stdin)',
  '          message=$(cat "$qa_nf")',
  '          rm -f "$qa_nf"',
  '        else',
  '          [ -f "$1" ] || qa_die "handoff: --note-file not found: $1"',
  '          message=$(cat "$1")',
  '        fi',
  '        ;;',
  '      --draft) publish=0 ;;',
  '      -*) qa_die "handoff: unknown option $1" ;;',
  '      *) if [ -z "$recipient" ]; then recipient=$1; else qa_die "handoff: unexpected arg $1"; fi ;;',
  '    esac',
  '    shift',
  '  done',
  '  [ -n "$recipient" ] || qa_die "handoff: recipient required (handoff <recipient> [-m msg] [--attach agent] [--file path])"',
  '  case $recipient in',
  '    */*|.|..) qa_die "handoff: invalid recipient \'$recipient\'" ;;',
  '  esac',
  '  # Refuse an address that cannot be delivered, rather than queueing a parcel that bounces where',
  '  # only the host sees it. Named the same way `reply --to` refuses an unknown parcel.',
  '  if [ -n "$QA_GRAPH" ] && ! qa_in_list "$recipient" "$QA_ROSTER"; then',
  '    printf \'agent.sh: %s: "%s" is not an agent.\\n\' "$mode" "$recipient" >&2',
  '    printf \'  roster: %s\\n\' "$QA_ROSTER" >&2',
  '    qa_die "$mode: address one of those (the roster refreshes on launch and on quimby sync)"',
  '  fi',
  '  # An --attach naming no agent fails host-side as a FAILED carry, which retries every cycle —',
  '  # so it warns forever rather than once. Cheaper to refuse here.',
  '  if [ -n "$QA_GRAPH" ] && [ -n "$attach" ] && ! qa_in_list "$attach" "$QA_ROSTER"; then',
  '    printf \'agent.sh: %s: --attach "%s" is not an agent.\\n\' "$mode" "$attach" >&2',
  '    printf \'  roster: %s\\n\' "$QA_ROSTER" >&2',
  '    qa_die "$mode: attach one of those, or drop --attach to send your own work"',
  '  fi',
  '  # An escalation aimed outside the permitted set is silently normalized to an ordinary advisory',
  '  # by the host — delivered, but waking nobody. That silence is the whole failure, so name it.',
  '  if [ -n "$QA_GRAPH" ] && [ "$mode" = escalate ]; then',
  '    if [ -z "$QA_ESCALATE" ]; then',
  "      printf 'agent.sh: escalate: you have no escalation target.\\n' >&2",
  '      qa_die "escalate: everything you send is advisory — use handoff, or record it with status"',
  '    fi',
  '    if ! qa_in_list "$recipient" "$QA_ESCALATE"; then',
  '      printf \'agent.sh: escalate: you may not escalate to "%s".\\n\' "$recipient" >&2',
  '      printf \'  permitted: %s\\n\' "$QA_ESCALATE" >&2',
  '      qa_die "escalate: name exactly one of those (an unpermitted escalation wakes nobody)"',
  '    fi',
  '  fi',
  '  [ "$mode" != delegate ] || [ -n "$message" ] || qa_die "delegate: message required"',
  '  # An escalation or a reply with no body is a wake carrying nothing — the recipient is',
  '  # interrupted and sent to read an empty note. Refuse rather than deliver that.',
  '  [ "$mode" != escalate ] || [ -n "$message" ] ||',
  '    qa_die "escalate: -m (or --note-file) required — summoning someone with no explanation wastes the interrupt"',
  '  [ "$mode" != reply ] || [ -n "$message" ] ||',
  '    qa_die "reply: -m (or --note-file) required — an answer needs a body"',
  '  # A note-less handoff is legitimate (a pure diff), but a note-less one carrying ATTACHED FILES',
  '  # is nearly always this mistake: --file attaches, it does not supply the body. Say so here,',
  '  # where it can still be fixed, rather than delivering an empty note to a peer.',
  '  if [ -z "$message" ] && [ -n "$files" ]; then',
  '    echo "agent.sh: WARNING publishing with an EMPTY note while attaching files." >&2',
  '    echo "          --file ATTACHES a file; it does not supply the note body (status --file does)." >&2',
  '    echo "          Use -m or --note-file <path> for the body." >&2',
  '  fi',
  '  [ "$mode" != reply ] || [ -n "$replyto" ] || qa_die "reply: --to <parcel> required (the question you are answering)"',
  '  # Fail here, not silently at the host: the reply-interrupt is honored only if the named parcel',
  '  # really reached this inbox, so a wrong name would publish fine and then wake nobody.',
  '  if [ "$mode" = reply ] && [ ! -d "$ROOT/handoff/in/received/$replyto" ] \\',
  '     && [ ! -d "$ROOT/handoff/in/processed/$replyto" ] \\',
  '     && ! grep -qxF "$replyto" "$ROOT/handoff/in/processed.ledger" 2>/dev/null; then',
  '    printf \'agent.sh: reply: "%s" is not a parcel you received.\\n\' "$replyto" >&2',
  "    printf 'Your inbox holds:\\n' >&2",
  '    ls -1 "$ROOT/handoff/in/received" 2>/dev/null | sed \'s/^/  /\' >&2 || true',
  '    qa_die "reply: use one of those names, or send an ordinary handoff instead"',
  '  fi',
  '  # The interrupt-intent tag by verb; the host validates it against the directs graph (§6).',
  "  fm=''",
  '  case $mode in',
  "    delegate) fm='delegated: true' ;;",
  "    escalate) fm='escalate: true' ;;",
  "    ask) fm='expects-reply: true' ;;",
  '    reply) fm="reply-to: $replyto" ;;',
  '  esac',
  '  draft="$ROOT/handoff/out/draft/$recipient"',
  '  rm -rf "$draft"',
  '  qa_mkdir "$draft"',
  // A leading '---' would be read as options by some printf implementations, so lead with %s.
  '  if [ -n "$fm" ] || [ -n "$attach" ]; then',
  "    printf '%s\\n' '---' > \"$draft/README.md\"",
  '    [ -z "$fm" ] || printf \'%s\\n\' "$fm" >> "$draft/README.md"',
  '    [ -z "$attach" ] || printf \'attach: %s\\n\' "$attach" >> "$draft/README.md"',
  "    printf '%s\\n' '---' >> \"$draft/README.md\"",
  '    printf \'%s\\n\' "$message" >> "$draft/README.md"',
  '  else',
  '    printf \'%s\\n\' "$message" > "$draft/README.md"',
  '  fi',
  '  for f in $files; do',
  '    [ -f "$f" ] || qa_die "handoff: --file not found: $f"',
  '    cp "$f" "$draft/"',
  '  done',
  '  if [ "$publish" -eq 0 ]; then',
  '    # Loud, because the gap between "I wrote it up" and "I sent it" is real and has been reported',
  '    # by an agent about itself: it told the user it had reported a finding when the parcel was',
  '    # still sitting in draft.',
  '    echo "agent.sh: DRAFTED, NOT SENT — parcel for \'$recipient\' is in handoff/out/draft/."',
  '    echo "          Nobody has it yet. Publish with: ./agent.sh publish $recipient"',
  '    return 0',
  '  fi',
  '  qa_publish "$recipient"',
  '}',
  '',
  'cmd_inbox() {',
  '  if [ $# -gt 0 ]; then sub=$1; shift; else sub=list; fi',
  '  case $sub in',
  '    list|ls)',
  '      rcv="$ROOT/handoff/in/received"',
  '      # A missing tray is empty, not a reason to return: the buried-parcel check below still has',
  '      # to run, and it is the one report that would otherwise never be printed.',
  '      [ -d "$rcv" ] || rcv="$ROOT/handoff/in/received-absent"',
  '      found=0',
  '      for d in "$rcv"/*/; do',
  '        [ -d "$d" ] || continue',
  '        found=1',
  '        name=$(basename "$d")',
  "        head1='(no note)'",
  '        [ -f "$d/README.md" ] && head1=$(head -n 1 "$d/README.md")',
  "        tag=''",
  '        # How MUCH code, not just that there is some. A sender routinely believes it sent one',
  '        # commit when the cumulative parcel carried six, and the receiver is the party that can',
  '        # still catch it before landing — but only if the number is in front of it.',
  '        if [ -f "$d/squashed.diff" ]; then',
  '          qa_nc=0',
  '          [ -d "$d/commits" ] && qa_nc=$(ls -1 "$d/commits" 2>/dev/null | wc -l | tr -d " ")',
  '          if [ "$qa_nc" -gt 0 ]; then tag=" [diff: $qa_nc commit(s)]"; else tag=\' [diff]\'; fi',
  '        fi',
  '        qa_nf=$(qa_attachment_count "$d")',
  '        if [ "$qa_nf" -gt 0 ]; then tag="$tag [+$qa_nf file(s)]"; fi',
  '        # The interrupt class comes from meta.yaml, which the HOST stamps — never from the note',
  '        # prose. A sender-typed "TO:"/"URGENT:" prefix cannot be enforced and decays silently:',
  '        # a reader cannot tell "not for me" from "sender forgot". These fields already exist, so',
  '        # the cost of surfacing them is zero for the sender and zero for you.',
  '        # `from` is already the parcel-name prefix and `to` is always you, so neither is shown.',
  '        m="$d/meta.yaml"',
  '        if [ -f "$m" ]; then',
  '          if grep -Eq \'^userDirected: *true\' "$m"; then tag="$tag [user-directed]"; fi',
  '          if grep -Eq \'^escalation: *true\' "$m"; then tag="$tag [escalation]"; fi',
  '          if grep -Eq \'^expectsReply: *true\' "$m"; then tag="$tag [awaiting your reply]"; fi',
  '          if grep -Eq \'^replyTo: *[^ ]\' "$m"; then tag="$tag [reply]"; fi',
  '        fi',
  '        printf \'%s%s — %s\\n\' "$name" "$tag" "$head1"',
  '      done',
  '      [ "$found" -eq 1 ] || echo \'(inbox empty)\'',
  '      # Surface parcels sitting in the PROCESSED archive that nobody ever opened. These are work',
  '      # closed without being read — the state an agent lands in after a bulk close it should not',
  '      # have made. Nothing else announces them: the host reminder sweep only watches `received`,',
  '      # so without this line a buried parcel is invisible from every direction.',
  '      qa_buried=0',
  '      for d in "$ROOT/handoff/in/processed"/*/; do',
  '        [ -d "$d" ] || continue',
  '        qa_b=$(basename "$d")',
  '        grep -qxF "$qa_b" "$ROOT/handoff/in/.opened" 2>/dev/null && continue',
  '        qa_buried=$((qa_buried + 1))',
  '        [ "$qa_buried" -gt 20 ] || printf \'  (unopened, processed) %s\\n\' "$qa_b"',
  '      done',
  '      if [ "$qa_buried" -gt 0 ]; then',
  '        [ "$qa_buried" -le 20 ] || printf \'  ... and %s more\\n\' "$((qa_buried - 20))"',
  '        printf \'%s parcel(s) were closed without ever being read. Read one with inbox show <p>,\\n\' "$qa_buried"',
  "        echo 'or put it back in the tray with: ./agent.sh inbox reopen <p>'",
  '      fi',
  '      ;;',
  '    show)',
  "      [ $# -gt 0 ] || qa_die 'inbox show <parcel>'",
  '      p="$ROOT/handoff/in/received/$1"',
  '      # A processed parcel is still READABLE. Closing it says you are finished acting on it, not',
  '      # that you may never look again — and an agent whose tray was bulk-closed before the',
  '      # opened-gate existed can only reach its buried work through this fallback.',
  '      qa_buried=0',
  '      if [ ! -d "$p" ] && [ -d "$ROOT/handoff/in/processed/$1" ]; then',
  '        p="$ROOT/handoff/in/processed/$1"',
  '        qa_buried=1',
  "        echo '── already processed (reopen it with: ./agent.sh inbox reopen '\"$1\"') ──'",
  '      fi',
  '      qa_await_dir "$p" || qa_die "inbox: parcel \'$1\' announced but not landed (retried — a mount-sync lag or a stale name). Run \'./agent.sh inbox\' to see what did arrive, or ask the sender to resend."',
  '      # Reading a parcel out of the PROCESSED archive deliberately does not mark it engaged: that',
  '      # would clear the GC protection below and let the next host sync delete the very thing you',
  '      # just found. Reopen it if you mean to act on it.',
  '      [ "$qa_buried" -eq 1 ] || qa_mark_opened "$1"',
  '      # The ROUTING, printed above the note and read from host-stamped meta.yaml. This answers',
  '      # "is this mine?" authoritatively, and it has to appear BEFORE the prose, because the note',
  '      # is the wrong place to look for that answer and agents have looked there. A parcel is in',
  '      # your inbox because the courier put it there; an addressee line written by a sender is not',
  '      # addressing, and treating a missing or unfamiliar one as "not mine" refuses work that was',
  '      # genuinely routed to you.',
  '      if [ -f "$p/meta.yaml" ]; then',
  '        qa_from=$(sed -n \'s/^from: *//p\' "$p/meta.yaml" | head -n 1)',
  '        qa_to=$(sed -n \'s/^to: *//p\' "$p/meta.yaml" | head -n 1)',
  '        if [ -n "$qa_from" ] || [ -n "$qa_to" ]; then',
  '          # Explicit guards rather than a shell default-expansion: no line in this script may',
  '          # carry a brace expansion, so no line can be mistaken for a JS template literal.',
  '          [ -n "$qa_from" ] || qa_from=\'?\'',
  '          [ -n "$qa_to" ] || qa_to=\'you\'',
  '          printf \'── delivered by quimby: from %s → to %s ──\\n\' "$qa_from" "$qa_to"',
  '        fi',
  '      fi',
  '      [ ! -f "$p/meta.yaml" ] || ! grep -Eq \'^userDirected: *true\' "$p/meta.yaml" || echo \'── user-directed work (host-stamped) ──\'',
  '      [ -f "$p/README.md" ] && { echo \'── note ──\'; cat "$p/README.md"; }',
  '      if [ -f "$p/squashed.diff" ]; then',
  "        echo ''",
  "        echo '── diffstat ──'",
  '        git apply --stat "$p/squashed.diff" 2>/dev/null || echo \'(unable to stat diff)\'',
  '      fi',
  '      if [ "$(qa_attachment_count "$p")" -gt 0 ]; then',
  "        echo ''",
  "        echo '── files (delivered INTO YOUR INBOX, not into repo/) ──'",
  '        for qa_af in "$p"/*; do',
  '          qa_is_parcel_file "$qa_af" || continue',
  '          printf \'  %s\\n\' "$qa_af"',
  '        done',
  "        echo '  They are outside repo/, so git cannot see them and nothing carries them back.'",
  "        echo '  Copy one in if you need it built against — and gitignore it there if you do.'",
  '      fi',
  '      ;;',
  '    done)',
  "      [ $# -gt 0 ] || qa_die 'inbox done <parcel>... | --all'",
  '      qa_mkdir "$ROOT/handoff/in/processed"',
  '      # `--all` and multiple names exist because one-at-a-time made a backlog UNCLEARABLE. An',
  '      # agent that fell behind by a few hundred parcels would have had to run this once per',
  '      # parcel, so it never drained, the tray only grew, and the reminder sweep poked it forever',
  '      # about work it had already read. That is not indiscipline; it is an interface with no',
  '      # bulk verb.',
  '      if [ "$1" = "--all" ]; then',
  '        qa_n=0',
  '        qa_kept=0',
  '        for d in "$ROOT/handoff/in/received"/*/; do',
  '          [ -d "$d" ] || continue',
  '          qa_b=$(basename "$d")',
  '          # ONLY what you have opened. Bulk-closing unopened parcels is discarding work you never',
  '          # read — agents did exactly that, emptied the tray, and then reported messages missing.',
  '          # They were right. Closing is a statement that you are finished with something, which',
  '          # you cannot be if you never looked at it.',
  '          if ! grep -qxF "$qa_b" "$ROOT/handoff/in/.opened" 2>/dev/null; then',
  '            qa_kept=$((qa_kept + 1))',
  '            # NAME the kept ones. A count tells you something was held back; only the name tells',
  '            # you WHICH, and these are precisely the parcels nobody has read. The closed ones get',
  '            # a count instead: you already opened them, and printing several hundred names into',
  '            # your own context is the token cost this command exists to avoid.',
  '            #',
  '            # The cap is deliberately high. Names are truncated in GLOB order, so a low cap can',
  '            # drop the very parcel worth surfacing — and past ~50 unopened the actionable fact is',
  '            # the total, not which ones: an agent holding that many has read none of them.',
  '            [ "$qa_kept" -gt 50 ] || printf \'          - %s\\n\' "$qa_b" >&2',
  '            continue',
  '          fi',
  '          rm -rf "$ROOT/handoff/in/processed/$qa_b"',
  '          mv "$d" "$ROOT/handoff/in/processed/$qa_b" || continue',
  '          qa_n=$((qa_n + 1))',
  '        done',
  '        printf \'agent.sh: marked %s opened parcel(s) processed (moved to handoff/in/processed — nothing is deleted)\\n\' "$qa_n"',
  '        if [ "$qa_kept" -gt 0 ]; then',
  '          [ "$qa_kept" -le 50 ] || printf \'          ... and %s more\\n\' "$((qa_kept - 50))" >&2',
  '          printf \'agent.sh: KEPT %s parcel(s) you have not opened (named above) — read one with\\n\' "$qa_kept" >&2',
  '          echo "          ./agent.sh inbox show <parcel>, or close it deliberately with inbox done <parcel>." >&2',
  '        fi',
  '        return 0',
  '      fi',
  '      for qa_name in "$@"; do',
  '        p="$ROOT/handoff/in/received/$qa_name"',
  '        qa_await_dir "$p" || qa_die "inbox: no parcel \'$qa_name\'"',
  '        dest="$ROOT/handoff/in/processed/$qa_name"',
  '        rm -rf "$dest"',
  '        mv "$p" "$dest"',
  '        # Naming a parcel to close it IS engagement, so it counts the same as having opened it.',
  '        # Without this the host GC would protect a parcel you deliberately finished with, and the',
  '        # archive would never drain.',
  '        qa_mark_opened "$qa_name"',
  '        echo "agent.sh: marked \'$qa_name\' processed"',
  '      done',
  '      ;;',
  '    reopen)',
  "      [ $# -gt 0 ] || qa_die 'inbox reopen <parcel>...'",
  '      qa_mkdir "$ROOT/handoff/in/received"',
  '      for qa_name in "$@"; do',
  '        p="$ROOT/handoff/in/processed/$qa_name"',
  '        [ -d "$p" ] || qa_die "inbox: no processed parcel \'$qa_name\' (it may have been swept by a host sync — ask the sender to resend)"',
  '        dest="$ROOT/handoff/in/received/$qa_name"',
  '        rm -rf "$dest"',
  '        mv "$p" "$dest"',
  '        echo "agent.sh: reopened \'$qa_name\' — it is back in your inbox"',
  '      done',
  '      ;;',
  '    *) qa_die "inbox: unknown subcommand \'$sub\' (list | show <p> | done <p>... | done --all | reopen <p>...)" ;;',
  '  esac',
  '}',
  '',
  '# attest formats the quimby-attest block the host parser expects and fills atCommit from the repo',
  "# HEAD, so the agent can't mis-key it or paste a wrong hash. The agent runs the check and states",
  "# the result; this only records it. A dirty tree is warned about — atCommit wouldn't cover it.",
  'cmd_attest() {',
  "  command=''",
  "  result=''",
  "  summary=''",
  '  while [ $# -gt 0 ]; do',
  '    case $1 in',
  '      --command) shift; [ $# -gt 0 ] || qa_die "attest: --command needs a value"; command=$1 ;;',
  '      --result) shift; [ $# -gt 0 ] || qa_die "attest: --result needs pass|fail"; result=$1 ;;',
  '      --summary) shift; [ $# -gt 0 ] || qa_die "attest: --summary needs a value"; summary=$1 ;;',
  '      -*) qa_die "attest: unknown option $1" ;;',
  '      *) qa_die "attest: unexpected arg $1" ;;',
  '    esac',
  '    shift',
  '  done',
  '  [ -n "$command" ] || qa_die "attest: --command required (the check you ran, e.g. \'npm run ci\')"',
  '  case $result in',
  '    pass|fail) ;;',
  "    *) qa_die 'attest: --result must be pass or fail' ;;",
  '  esac',
  '  repo="$ROOT/repo"',
  '  head=$(git -C "$repo" rev-parse --short HEAD 2>/dev/null) || qa_die \'attest: cannot read repo HEAD — commit your work first\'',
  '  if [ -n "$(git -C "$repo" status --porcelain 2>/dev/null)" ]; then',
  '    echo "agent.sh: WARNING uncommitted changes in repo — atCommit ($head) won\'t cover them; commit first, then re-attest" >&2',
  '  fi',
  '  status="$ROOT/status.md"',
  '  printf \'\\n```quimby-attest\\n\' >> "$status"',
  '  printf \'command: %s\\n\' "$command" >> "$status"',
  '  printf \'result: %s\\n\' "$result" >> "$status"',
  '  [ -n "$summary" ] && printf \'summary: %s\\n\' "$summary" >> "$status"',
  '  printf \'atCommit: %s\\n\' "$head" >> "$status"',
  '  printf \'```\\n\' >> "$status"',
  '  echo "agent.sh: attested $result @ $head"',
  '}',
  '',
  '# How many commits the delivered base is ahead of HEAD. Empty/0 when there is nothing to say:',
  '# no repo, no quimby/base yet (never synced), or already current.',
  'qa_base_behind() {',
  '  repo="$ROOT/repo"',
  '  [ -d "$repo" ] || return 0',
  '  git -C "$repo" rev-parse -q --verify quimby/base >/dev/null 2>&1 || return 0',
  '  git -C "$repo" rev-list --count HEAD..quimby/base 2>/dev/null || true',
  '}',
  '',
  '# Printed after EVERY command, and silent unless the base actually moved. The host now delivers',
  "# peers' landed work as the quimby/base tag instead of rebasing your repo underneath you, so",
  '# nothing else would tell you the floor shifted — and a base you never apply is how your next',
  '# diff quietly re-carries work that already shipped.',
  'qa_base_notice() {',
  '  n=$(qa_base_behind)',
  '  [ -n "$n" ] && [ "$n" != "0" ] || return 0',
  '  echo "" >&2',
  '  echo "agent.sh: quimby/base is $n commit(s) ahead of you — peers\' work landed since your seed." >&2',
  '  echo "          Apply it at a clean boundary (not mid-edit): ./agent.sh rebase" >&2',
  '}',
  '',
  '# Unread parcels, reported after every command like the base notice and silent at zero.',
  '#',
  '# This is the self-service half of delivery. An ADVISORY parcel deliberately does not wake you,',
  '# so without this the only thing that could tell you it arrived is the host reminder sweep — which',
  '# needs `quimby serve` running, fires at most every 10 minutes, and gives up after 3 tries. Until',
  '# then a delivered parcel is invisible and the human ends up relaying "check your inbox", which is',
  '# the messenger problem quimby exists to remove. Reading a count off the tray costs nothing and',
  '# needs no server, no nudge, and no config.',
  'qa_inbox_notice() {',
  '  rcv="$ROOT/handoff/in/received"',
  '  [ -d "$rcv" ] || return 0',
  '  n=0',
  '  for d in "$rcv"/*/; do',
  '    if [ -d "$d" ]; then n=$((n + 1)); fi',
  '  done',
  '  [ "$n" -gt 0 ] || return 0',
  '  echo "" >&2',
  '  echo "agent.sh: $n unread parcel(s) in your inbox — ./agent.sh inbox to triage" >&2',
  '}',
  '',
  '# Name the dirty files instead of only refusing. An agent facing a bare refusal and hundreds of',
  '# dirty paths has nothing to reason from and reaches for `git checkout .` — which is exactly what',
  '# the refusal exists to prevent. The tool cannot know which edits are YOURS; it cannot read',
  '# intent, and delivered content and hand-written work look identical in a working tree. What it',
  '# CAN say is which of them the incoming base also changes: discarding one of those reverts work',
  '# that already landed, silently and with no conflict, so that is the subset worth naming.',
  'qa_dirty_report() {',
  '  qa_repo=$1',
  '  qa_st=$(mktemp)',
  '  qa_inc=$(mktemp)',
  '  git -C "$qa_repo" status --porcelain > "$qa_st" 2>/dev/null || true',
  '  git -C "$qa_repo" diff --name-only HEAD..quimby/base > "$qa_inc" 2>/dev/null || true',
  '  qa_n=$(wc -l < "$qa_st" | tr -d " ")',
  '  qa_shown=0',
  '  qa_over=0',
  '  while IFS= read -r qa_line; do',
  '    [ -n "$qa_line" ] || continue',
  '    # porcelain is XY<space>path; a rename carries "old -> new" and the NEW name is the one that',
  '    # matters for an overlap check.',
  '    qa_path=$(printf "%s" "$qa_line" | cut -c4-)',
  '    # sed, not a suffix-stripping parameter expansion: this file bans the brace-expansion form',
  '    # outright so nothing here can be mistaken for template interpolation, and a pinned test',
  '    # enforces that ban across the whole script.',
  '    case $qa_path in *" -> "*) qa_path=$(printf "%s" "$qa_path" | sed "s/.* -> //") ;; esac',
  '    if grep -qxF "$qa_path" "$qa_inc" 2>/dev/null; then',
  '      qa_over=$((qa_over + 1))',
  '      if [ "$qa_shown" -lt 20 ]; then',
  '        echo "            $qa_path   <- the incoming base changes this too" >&2',
  '      fi',
  '    else',
  '      if [ "$qa_shown" -lt 20 ]; then echo "            $qa_path" >&2; fi',
  '    fi',
  '    qa_shown=$((qa_shown + 1))',
  '  done < "$qa_st"',
  '  # Bounded on purpose: a 300-file dump is as unreadable as no list at all, and the count above',
  '  # already carries the scale.',
  '  if [ "$qa_n" -gt 20 ]; then echo "            … and $((qa_n - 20)) more" >&2; fi',
  '  if [ "$qa_over" -gt 0 ]; then',
  '    echo "          $qa_over of these are also changed by the incoming base. Discarding one of those" >&2',
  '    echo "          reverts work that already landed — no conflict, nothing downstream to catch it." >&2',
  '  fi',
  '  rm -f "$qa_st" "$qa_inc"',
  '}',
  '',
  '# Parcel attachments: every FILE in a parcel that quimby does not own. A parcel is flat, so this',
  '# is just "everything that is not the note, the diff, or the manifest" — `commits/` is a',
  '# directory and drops out on its own.',
  '#',
  '# Worth naming rather than leaving to the note: an attachment is the whole reason some parcels',
  '# exist (an operator hand-carrying a file an agent could not download), and a parcel that showed',
  '# only its note and diffstat left that file invisible unless the sender happened to mention it.',
  'qa_is_parcel_file() {',
  '  case $(basename "$1") in',
  '    README.md|squashed.diff|uncommitted.diff|meta.yaml) return 1 ;;',
  '  esac',
  '  [ -f "$1" ]',
  '}',
  '',
  'qa_attachment_count() {',
  '  qa_ac=0',
  '  for qa_af in "$1"/*; do',
  '    qa_is_parcel_file "$qa_af" || continue',
  '    qa_ac=$((qa_ac + 1))',
  '  done',
  '  printf \'%s\\n\' "$qa_ac"',
  '}',
  '',
  '# Apply the delivered base. Deliberately refuses on a dirty tree: the entire reason the host',
  '# stopped doing this for you is that only YOU know when your tree is at a safe point, and',
  '# replaying over uncommitted work is how a pre-sync copy of a file gets resurrected on top of a',
  "# peer's just-landed change — silently, with no conflict. Commit first; then this is auditable.",
  'cmd_rebase() {',
  '  repo="$ROOT/repo"',
  '  [ -d "$repo" ] || qa_die "rebase: no repo/ in $ROOT"',
  '  git -C "$repo" rev-parse -q --verify quimby/base >/dev/null 2>&1 ||',
  '    qa_die "rebase: no quimby/base yet — the host has not delivered a base to this agent"',
  '  n=$(git -C "$repo" rev-list --count HEAD..quimby/base 2>/dev/null || echo 0)',
  '  if [ "$n" = "0" ]; then',
  '    # Already on the base — but the SEED may still be behind, and this is the path where that',
  '    # gets stuck: an agent that applied its base under an older tool has nothing left to rebase,',
  '    # so returning here without retagging means the seed can never catch up and every capture',
  '    # keeps measuring against a stale baseline. Advancing it here is what lets that self-heal.',
  '    # `-q --verify`, not a bare rev-parse: on an unknown ref git ECHOES THE REF NAME to stdout',
  '    # and exits non-zero, so a plain capture yields the string "quimby/seed" rather than empty —',
  '    # which reads as a seed that exists and disagrees, and retags a repo that has no seed at all.',
  '    qa_seed=$(git -C "$repo" rev-parse -q --verify quimby/seed 2>/dev/null || true)',
  '    # Only when the seed is READABLE and different. An unreadable one is not evidence of',
  '    # staleness, and is not a reason to write a tag — the same rule the host applies.',
  '    if [ -n "$qa_seed" ] && [ "$qa_seed" != "$(git -C "$repo" rev-parse quimby/base)" ]; then',
  '      git -C "$repo" tag -f quimby/seed quimby/base >/dev/null 2>&1 &&',
  '        echo "agent.sh: already on quimby/base; advanced your seed to match (it was behind)"',
  '      return 0',
  '    fi',
  '    echo "agent.sh: already up to date with quimby/base"',
  '    return 0',
  '  fi',
  '  if [ -n "$(git -C "$repo" status --porcelain 2>/dev/null)" ]; then',
  '    echo "agent.sh: rebase: your tree is dirty, so the base was not applied. Replaying over" >&2',
  '    echo "          uncommitted work is exactly what this refusal prevents. Uncommitted:" >&2',
  '    qa_dirty_report "$repo"',
  '    qa_die "rebase: commit your work (git add <your paths>; git commit), then re-run' +
    ' ./agent.sh rebase. Discard only what you are certain is not yours."',
  '  fi',
  '  qa_target=$(git -C "$repo" rev-parse quimby/base)',
  '  git -C "$repo" rebase quimby/base ||',
  '    qa_die "rebase: conflicts — resolve them, git add, then: git rebase --continue. Re-run',
  '      ./agent.sh rebase afterwards so your seed is advanced too."',
  '  # ADVANCE THE SEED to what was just applied. Not bookkeeping — `quimby/seed` is the baseline',
  '  # your work is CAPTURED against, so leaving it behind makes every handoff and merge carry the',
  "  # peers' already-landed commits as if they were yours. An agent that applied a base one day",
  '  # stale would ship 85 commits and 146 files in place of its own 7 and 25.',
  '  #',
  '  # The host used to do this in the same breath as the rebase it performed for you. Now that YOU',
  '  # apply the base, you retag too — otherwise the two halves of that operation come apart.',
  '  git -C "$repo" tag -f quimby/seed "$qa_target" >/dev/null 2>&1 ||',
  '    echo "agent.sh: WARNING rebased, but could not advance quimby/seed — your next handoff will' +
    ' over-capture. Tell the host." >&2',
  '  echo "agent.sh: rebased onto quimby/base ($(git -C "$repo" rev-parse --short quimby/base)); seed advanced"',
  '}',
  '',
  '# The provenance of a status mirror, printed so its CONTENT is never read without it.',
  '#',
  '# A mirror is a push cache the host fills; it can silently never arrive (a stopped or sleeping',
  '# server writes nothing, ever). The distinction is already in the file — a real snapshot carries',
  "# an 'Updated:' line and the creation-time placeholder deliberately does not — but `cat` threw it",
  '# away, and three agents each invented a different explanation for the same never-populated',
  '# mirror ("builders wrote stale content", "distribution died Jul 31"). Never-reported and',
  '# reported-long-ago look identical if you only print the body.',
  'qa_mirror_age() {',
  '  updated=$(sed -n \'s/^Updated: *//p\' "$1" 2>/dev/null | head -n 1)',
  '  if [ -z "$updated" ]; then',
  "    echo 'never reported'",
  '    return 0',
  '  fi',
  '  # Age in whole days from the file itself, so this needs no date parsing beyond what sh has.',
  '  now=$(date +%s 2>/dev/null || echo 0)',
  '  then_=$(date -r "$1" +%s 2>/dev/null || echo 0)',
  '  if [ "$now" -gt 0 ] && [ "$then_" -gt 0 ]; then',
  '    days=$(( (now - then_) / 86400 ))',
  '    if [ "$days" -gt 0 ]; then',
  '      printf \'updated %sd ago\\n\' "$days"',
  '      return 0',
  '    fi',
  '  fi',
  "  echo 'updated recently'",
  '}',
  '',
  'cmd_peers() {',
  '  sdir="$ROOT/status"',
  '  if [ $# -gt 0 ]; then',
  '    f="$sdir/$1.md"',
  '    [ -f "$f" ] || qa_die "peers: no status mirror for \'$1\'"',
  '    printf \'── %s (%s) ──\\n\' "$1" "$(qa_mirror_age "$f")"',
  '    cat "$f"',
  '    return 0',
  '  fi',
  '  [ -d "$sdir" ] || { echo \'(no peers)\'; return 0; }',
  '  found=0',
  '  for f in "$sdir"/*.md; do',
  '    [ -f "$f" ] || continue',
  '    found=1',
  '    p=$(basename "$f" .md)',
  '    # Annotate the edge, so the roster is not a flat list of names to infer a hierarchy from.',
  "    tag=''",
  '    qa_in_list "$p" "$QA_DIRECTED_BY" && tag=\'  (directs you — their work is authoritative)\'',
  '    if [ -z "$tag" ] && qa_in_list "$p" "$QA_DIRECTS"; then',
  "      tag='  (you direct — a handoff wakes them)'",
  '    fi',
  '    if [ -z "$tag" ] && qa_in_list "$p" "$QA_ESCALATE"; then',
  "      tag='  (you may escalate here)'",
  '    fi',
  '    printf \'%s%s  [%s]\\n\' "$p" "$tag" "$(qa_mirror_age "$f")"',
  '  done',
  '  [ "$found" -eq 1 ] || echo \'(no peers)\'',
  '}',
  '',
  '# A light repo-health mechanism fact for `wake` (not policy): is the agent clone wedged?',
  'qa_wake_repo_health() {',
  '  gd="$ROOT/repo/.git"',
  '  [ -d "$gd" ] || return 0',
  '  if [ -d "$gd/rebase-merge" ] || [ -d "$gd/rebase-apply" ]; then',
  '    echo "! repo is mid-rebase - resolve before new work (git -C repo rebase --continue / --abort)"',
  '  elif [ -f "$gd/MERGE_HEAD" ]; then',
  '    echo "! repo is mid-merge - resolve before new work (git -C repo merge --continue / --abort)"',
  '  fi',
  '}',
  '',
  '# One name-INDEPENDENT orientation packet. It derives "what is here" from durable state',
  '# (in/received minus in/processed - a `done` parcel is moved out, so received IS the unprocessed',
  '# set), never from the courier line - so an early / lost / duplicated announce is self-healing,',
  '# and `wake` is the safe first move on any wake-up. The granular verbs stay for drill-down.',
  'cmd_wake() {',
  '  qa_wake_repo_health',
  '  echo "-- assignment --"',
  '  if [ -s "$ROOT/assignment.md" ]; then head -n 3 "$ROOT/assignment.md"; else echo "(none set)"; fi',
  '  echo "-- status (your handoff to your successor) --"',
  '  if [ -s "$ROOT/status.md" ]; then head -n 3 "$ROOT/status.md"; else echo "(idle)"; fi',
  '  echo "-- inbox (unprocessed) --"',
  '  cmd_inbox list',
  '  echo "-- peers --"',
  '  cmd_peers',
  '  # Every mirror still a placeholder means the host has NEVER fed them — a stopped or sleeping',
  '  # server, not quiet peers. Called out here rather than in the per-command footer on purpose: if',
  '  # the server is down this condition holds forever, and a line on every invocation would train',
  '  # you to skim the footer that also carries the base and inbox notices.',
  '  if [ -d "$ROOT/status" ]; then',
  '    any=0',
  '    fed=0',
  '    newest=-1',
  '    qa_now=$(date +%s 2>/dev/null || echo 0)',
  '    for f in "$ROOT/status"/*.md; do',
  '      [ -f "$f" ] || continue',
  '      any=1',
  '      grep -q \'^Updated: \' "$f" 2>/dev/null || continue',
  '      fed=1',
  '      qa_t=$(date -r "$f" +%s 2>/dev/null || echo 0)',
  '      if [ "$qa_now" -gt 0 ] && [ "$qa_t" -gt 0 ]; then',
  '        qa_d=$(( (qa_now - qa_t) / 86400 ))',
  '        if [ "$newest" -lt 0 ] || [ "$qa_d" -lt "$newest" ]; then newest=$qa_d; fi',
  '      fi',
  '    done',
  '    if [ "$any" -eq 1 ] && [ "$fed" -eq 0 ]; then',
  '      echo "   (no peer has EVER reported — the host mirrors status, so this means its server is not"',
  '      echo "    running. Peer status is unavailable; do not read the placeholders as their state.)"',
  '    elif [ "$newest" -ge 2 ]; then',
  '      # The mixed case, which the all-placeholder check above misses entirely: some mirrors were',
  '      # fed once and then froze. "Everyone last reported 9 days ago" is not a quiet fleet, it is a',
  '      # stopped server — and read as peer state it invites exactly the wrong conclusions.',
  '      printf \'   (no peer status has been mirrored in %sd — the host writes these, so its server is\\n\' "$newest"',
  '      echo "    probably not running. Treat every peer status below as that old, not as current.)"',
  '    fi',
  '  fi',
  '}',
  '',
  'usage() {',
  "  cat <<'EOF'",
  'agent.sh — your Quimby coordination tool (mechanics only; judgment stays in instructions)',
  '',
  '  assignment              show the current assignment',
  '  assignment set -m msg|--file path|-',
  '                          replace the current assignment',
  '  wake                    one orientation packet (repo health, assignment, status, inbox, peers) -',
  '                          name-independent, so run it first on any wake-up (self-heals a raced announce)',
  '  status                  show your current status journal',
  '  status set -m msg|--file path|-',
  '                          replace your status journal',
  '  status append -m msg|--file path|-',
  '                          append to your status journal',
  '  status done [-m msg|--file path|-]',
  '                          append a done summary (default: "done.")',
  '  handoff <recipient> [-m msg | --note-file path] [--attach agent] [--file path] [--draft]',
  '                        author + atomically publish a parcel to a peer. Reports the commit count',
  '                        and range it carries — a parcel is CUMULATIVE since quimby/seed, so check',
  '                        that number against what you meant to send.',
  '                        -m / --note-file supply the NOTE BODY; --file ATTACHES a file alongside',
  '                        it and does not become the body (unlike status --file, which is content)',
  '  delegate <recipient> -m msg [--attach agent] [--file path] [--draft]',
  '                        (user-directed) mark a host-promoted directive',
  '  escalate <recipient> [-m msg]   summon your director upward (interrupts; no authority)',
  '  ask <recipient> -m msg          ask a question and get woken by the reply',
  '  reply <recipient> --to <parcel> -m msg   answer a question, waking the asker',
  '                        relay user-directed work to a peer',
  '  publish <recipient>   publish a parcel you drafted with --draft',
  "  inbox [list]          list delivered parcels. Each line PREVIEWS the note's first line and tags",
  '                        what kind it is ([user-directed] [escalation] [awaiting your reply] [reply]',
  '                        [diff: N commit(s)]), so you can triage the whole inbox without opening',
  '                        anything — and see how much code a parcel carries before you land it',
  "  inbox show <parcel>   print a parcel's note, diffstat and attached files IN FULL — there is no",
  '                        paging and no early exit, so open it when you mean to read all of it.',
  '                        Attachments live in the parcel dir, outside repo/, so nothing carries',
  '                        them back across the boundary',
  '  inbox done <parcel>... | --all',
  '                        mark parcels processed (moved to handoff/in/processed — never deleted).',
  '                        --all closes only the parcels you have OPENED with `inbox show`; anything',
  '                        unopened is kept, because closing it would discard work you never read',
  '  inbox reopen <parcel>...',
  '                        put a processed parcel back in the tray. `inbox` lists any that were',
  '                        closed without being read — reopen one to act on it',
  '  attest --command CMD --result pass|fail [--summary S]',
  '                        append a quimby-attest block (atCommit auto-filled from HEAD)',
  '  peers [name]          list peer status mirrors, or read one',
  '  rebase                apply the delivered base (quimby/base) onto your work. The host no longer',
  '                        rebases you underneath your own edits — it delivers the base and you apply',
  '                        it when your tree is clean. Every command reminds you when you are behind.',
  '',
  'QUOTING — a note passed as -m "..." is expanded by the SHELL before this tool sees it:',
  '  backticks, $ and \\ are rewritten, so `npm run ci` and $PATH vanish from your note with no',
  '  error and nothing to notice. Use single quotes for a short literal line, and --note-file',
  '  <path> (or - for stdin) for anything longer. Applies to every -m here, not just handoff.',
  '',
  "Delivery across the boundary is the host's job (quimby dispatch / merge); this",
  'tool only ever writes your own workspace.',
  'EOF',
  '}',
  '',
  'main() {',
  '  [ $# -gt 0 ] || { usage; exit 0; }',
  '  verb=$1',
  '  shift',
  '  case $verb in',
  '    help|-h|--help) usage; exit 0 ;;',
  '  esac',
  '  ROOT=$(qa_root) || qa_die "not inside an agent workspace (no handoff/ + assignment.md above $PWD)"',
  '  case $verb in',
  '    wake) cmd_wake "$@" ;;',
  '    handoff) cmd_handoff handoff "$@" ;;',
  '    delegate) cmd_handoff delegate "$@" ;;',
  '    escalate) cmd_handoff escalate "$@" ;;',
  '    ask) cmd_handoff ask "$@" ;;',
  '    reply) cmd_handoff reply "$@" ;;',
  '    publish) [ $# -gt 0 ] || qa_die \'publish <recipient>\'; qa_publish "$1" ;;',
  '    inbox) cmd_inbox "$@" ;;',
  '    attest) cmd_attest "$@" ;;',
  '    peers) cmd_peers "$@" ;;',
  '    assignment) cmd_assignment "$@" ;;',
  '    status) cmd_status "$@" ;;',
  '    rebase) cmd_rebase "$@" ;;',
  '    *) qa_die "unknown command \'$verb\' — run: ./agent.sh help" ;;',
  '  esac',
  '  # Ambient, not a nudge: these ride EVERY invocation and stay silent unless there is something',
  '  # to say. They are the whole passive-delivery signal — the host does not wake you for a moved',
  '  # base (it no longer moves it for you) or for an advisory parcel (it is not addressed at you),',
  '  # so this is how you find out without anyone relaying it.',
  '  # `inbox` and `wake` already print the tray, so repeating a count at them would be noise.',
  '  case $verb in',
  '    inbox|wake) ;;',
  '    *) qa_inbox_notice ;;',
  '  esac',
  '  qa_base_notice',
  '}',
  '',
  'main "$@"',
]

// Windows batch twin. Each JS line escapes `"`→`\"` and `\`→`\\`; backticks are literal. cmd has
// no `${...}`/`\n` semantics, so only backslashes (Windows paths) need doubling. Best-effort and
// unverified on Windows — the .sh above is canonical; this exists only for a Windows-hosted agent.
const CMD_LINES = [
  '@echo off',
  'setlocal enabledelayedexpansion',
  'rem agent.cmd — Windows twin of agent.sh (that file is canonical). Best-effort:',
  'rem remote sandboxes are POSIX, so this only matters for a Windows-hosted agent. If it misbehaves,',
  'rem the CLAUDE.md prose conventions are the fallback. Deps: cmd + git.',
  '',
  'rem The coordination graph, baked in by the host (see the .sh twin). Empty = nothing rendered.',
  'set "QA_GRAPH={{graph}}"',
  'set "QA_ROSTER={{roster}}"',
  'set "QA_ESCALATE={{escalate}}"',
  '',
  'call :find_root',
  'if "%ROOT%"=="" ( echo agent.cmd: not inside an agent workspace 1>&2 & exit /b 1 )',
  '',
  'set "VERB=%~1"',
  'if "%VERB%"=="" goto :usage',
  'shift',
  'if /I "%VERB%"=="help" goto :usage',
  'if /I "%VERB%"=="assignment" goto :assignment',
  'if /I "%VERB%"=="status" goto :status',
  'if /I "%VERB%"=="handoff" ( set "MODE=handoff" & goto :handoff )',
  'if /I "%VERB%"=="delegate" ( set "MODE=delegate" & goto :handoff )',
  'if /I "%VERB%"=="escalate" ( set "MODE=escalate" & goto :handoff )',
  'if /I "%VERB%"=="ask" ( set "MODE=ask" & goto :handoff )',
  'if /I "%VERB%"=="reply" ( set "MODE=reply" & goto :handoff )',
  'if /I "%VERB%"=="publish" goto :publish_cmd',
  'if /I "%VERB%"=="inbox" goto :inbox',
  'if /I "%VERB%"=="attest" goto :attest',
  'if /I "%VERB%"=="peers" goto :peers',
  "echo agent.cmd: unknown command '%VERB%' — run: agent.cmd help 1>&2",
  'exit /b 1',
  '',
  ':find_root',
  'set "ROOT="',
  'set "D=%CD%"',
  ':fr_loop',
  'if exist "%D%\\handoff" if exist "%D%\\assignment.md" ( set "ROOT=%D%" & exit /b 0 )',
  'for %%P in ("%D%\\..") do set "PARENT=%%~fP"',
  'if "%PARENT%"=="%D%" exit /b 0',
  'set "D=%PARENT%"',
  'goto :fr_loop',
  '',
  'rem Exit 0 when %~1 is NOT in the space-separated list %~2 (an empty list is never a mismatch),',
  'rem so the callers above read as `call :not_in_list ... && (complain)`.',
  ':not_in_list',
  'if "%~2"=="" exit /b 0',
  'for %%N in (%~2) do if /I "%%~N"=="%~1" exit /b 1',
  'exit /b 0',
  '',
  ':assignment',
  'set "SUB=%~1"',
  'if "%SUB%"=="" set "SUB=show"',
  'if /I "%SUB%"=="show" ( type "%ROOT%\\assignment.md" & exit /b 0 )',
  'if /I not "%SUB%"=="set" ( echo agent.cmd: assignment: unknown subcommand %SUB% 1>&2 & exit /b 1 )',
  'shift',
  'set "MSG="',
  'set "FILE="',
  ':as_loop',
  'if "%~1"=="" goto :as_done',
  'if /I "%~1"=="-m" ( set "MSG=%~2" & shift & shift & goto :as_loop )',
  'if /I "%~1"=="--message" ( set "MSG=%~2" & shift & shift & goto :as_loop )',
  'if /I "%~1"=="--file" ( set "FILE=%~2" & shift & shift & goto :as_loop )',
  'echo agent.cmd: assignment set: unexpected arg %~1 1>&2 & exit /b 1',
  ':as_done',
  'if not "%FILE%"=="" (',
  '  if "%FILE%"=="-" ( more > "%ROOT%\\assignment.md" ) else ( if not exist "%FILE%" ( echo agent.cmd: assignment set: --file not found: %FILE% 1>&2 & exit /b 1 ) & copy /y "%FILE%" "%ROOT%\\assignment.md" >nul )',
  ') else (',
  '  if "%MSG%"=="" ( echo agent.cmd: assignment set: provide -m or --file 1>&2 & exit /b 1 )',
  '  >"%ROOT%\\assignment.md" echo(%MSG%',
  ')',
  'echo agent.cmd: assignment set',
  'exit /b 0',
  '',
  ':status',
  'set "SUB=%~1"',
  'if "%SUB%"=="" set "SUB=show"',
  'if /I "%SUB%"=="show" ( type "%ROOT%\\status.md" & exit /b 0 )',
  'if /I not "%SUB%"=="set" if /I not "%SUB%"=="append" if /I not "%SUB%"=="done" ( echo agent.cmd: status: unknown subcommand %SUB% 1>&2 & exit /b 1 )',
  'shift',
  'set "MSG="',
  'set "FILE="',
  ':st_loop',
  'if "%~1"=="" goto :st_done',
  'if /I "%~1"=="-m" ( set "MSG=%~2" & shift & shift & goto :st_loop )',
  'if /I "%~1"=="--message" ( set "MSG=%~2" & shift & shift & goto :st_loop )',
  'if /I "%~1"=="--file" ( set "FILE=%~2" & shift & shift & goto :st_loop )',
  'echo agent.cmd: status %SUB%: unexpected arg %~1 1>&2 & exit /b 1',
  ':st_done',
  'if /I "%SUB%"=="done" if "%MSG%"=="" if "%FILE%"=="" set "MSG=done."',
  'if not "%FILE%"=="" (',
  '  if "%FILE%"=="-" ( set "TMP=%TEMP%\\quimby-status-%RANDOM%.tmp" & more > "!TMP!" & set "FILE=!TMP!" )',
  '  if not exist "%FILE%" ( echo agent.cmd: status %SUB%: --file not found: %FILE% 1>&2 & exit /b 1 )',
  '  if /I "%SUB%"=="set" ( copy /y "%FILE%" "%ROOT%\\status.md" >nul ) else ( type "%FILE%" >> "%ROOT%\\status.md" )',
  '  if defined TMP del "!TMP!" >nul 2>nul',
  ') else (',
  '  if "%MSG%"=="" ( echo agent.cmd: status %SUB%: provide -m or --file 1>&2 & exit /b 1 )',
  '  if /I "%SUB%"=="set" ( >"%ROOT%\\status.md" echo(%MSG% ) else ( >>"%ROOT%\\status.md" echo. & >>"%ROOT%\\status.md" echo(%MSG% )',
  ')',
  'echo agent.cmd: status %SUB%',
  'exit /b 0',
  '',
  ':handoff',
  'set "RECIP="',
  'set "MSG="',
  'set "ATTACH="',
  'set "REPLYTO="',
  'set "PUBLISH=1"',
  'set "FILES="',
  ':ho_loop',
  'if "%~1"=="" goto :ho_done',
  'if /I "%~1"=="-m" ( set "MSG=%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--message" ( set "MSG=%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--attach" ( set "ATTACH=%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--to" ( set "REPLYTO=%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--file" ( set FILES=!FILES! "%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--draft" ( set "PUBLISH=0" & shift & goto :ho_loop )',
  'if "!RECIP!"=="" ( set "RECIP=%~1" & shift & goto :ho_loop )',
  'echo agent.cmd: handoff: unexpected arg %~1 1>&2 & exit /b 1',
  ':ho_done',
  'if "%RECIP%"=="" ( echo agent.cmd: %MODE%: recipient required 1>&2 & exit /b 1 )',
  // Roster / escalation gate — the .sh twin's qa_in_list, in cmd. An empty list means the host
  // rendered nothing, so it passes rather than blocking a send on missing data.
  'if not "%QA_GRAPH%"=="" call :not_in_list "%RECIP%" "%QA_ROSTER%" && (',
  '  echo agent.cmd: %MODE%: "%RECIP%" is not an agent. 1>&2',
  '  echo   roster: %QA_ROSTER% 1>&2',
  '  exit /b 1',
  ')',
  'if not "%QA_GRAPH%"=="" if not "%ATTACH%"=="" call :not_in_list "%ATTACH%" "%QA_ROSTER%" && (',
  '  echo agent.cmd: %MODE%: --attach "%ATTACH%" is not an agent. 1>&2',
  '  echo   roster: %QA_ROSTER% 1>&2',
  '  exit /b 1',
  ')',
  'if not "%QA_GRAPH%"=="" if "%MODE%"=="escalate" if "%QA_ESCALATE%"=="" (',
  '  echo agent.cmd: escalate: you have no escalation target — everything you send is advisory. 1>&2',
  '  exit /b 1',
  ')',
  'if not "%QA_GRAPH%"=="" if "%MODE%"=="escalate" call :not_in_list "%RECIP%" "%QA_ESCALATE%" && (',
  '  echo agent.cmd: escalate: you may not escalate to "%RECIP%". 1>&2',
  '  echo   permitted: %QA_ESCALATE% 1>&2',
  '  exit /b 1',
  ')',
  'if "%MODE%"=="delegate" if "%MSG%"=="" ( echo agent.cmd: delegate: message required 1>&2 & exit /b 1 )',
  'if "%MODE%"=="reply" if "%REPLYTO%"=="" ( echo agent.cmd: reply: --to ^<parcel^> required 1>&2 & exit /b 1 )',
  // The interrupt-intent tag by verb; the host validates it against the directs graph (§6).
  'set "FM="',
  'if "%MODE%"=="delegate" set "FM=delegated: true"',
  'if "%MODE%"=="escalate" set "FM=escalate: true"',
  'if "%MODE%"=="ask" set "FM=expects-reply: true"',
  'if "%MODE%"=="reply" set "FM=reply-to: %REPLYTO%"',
  'set "DRAFT=%ROOT%\\handoff\\out\\draft\\%RECIP%"',
  'if exist "%DRAFT%" rmdir /s /q "%DRAFT%"',
  'mkdir "%DRAFT%" 2>nul',
  'if not "%FM%%ATTACH%"=="" (',
  '  >"%DRAFT%\\README.md" echo ---',
  '  if not "%FM%"=="" >>"%DRAFT%\\README.md" echo(%FM%',
  '  if not "%ATTACH%"=="" >>"%DRAFT%\\README.md" echo attach: %ATTACH%',
  '  >>"%DRAFT%\\README.md" echo ---',
  '  >>"%DRAFT%\\README.md" echo(%MSG%',
  ') else (',
  '  >"%DRAFT%\\README.md" echo(%MSG%',
  ')',
  'for %%F in (!FILES!) do if not "%%~F"=="" ( if not exist "%%~F" ( echo agent.cmd: handoff: --file not found: %%~F 1>&2 & exit /b 1 ) & copy /y "%%~F" "%DRAFT%\\" >nul )',
  'if "%PUBLISH%"=="0" ( echo agent.cmd: drafted parcel for \'%RECIP%\' & exit /b 0 )',
  'call :do_publish "%RECIP%"',
  'exit /b %ERRORLEVEL%',
  '',
  ':publish_cmd',
  'if "%~1"=="" ( echo agent.cmd: publish ^<recipient^> 1>&2 & exit /b 1 )',
  'call :do_publish "%~1"',
  'exit /b %ERRORLEVEL%',
  '',
  ':do_publish',
  'set "R=%~1"',
  'set "DR=%ROOT%\\handoff\\out\\draft\\%R%"',
  'if not exist "%DR%" ( echo agent.cmd: publish: no draft for \'%R%\' 1>&2 & exit /b 1 )',
  'if not exist "%ROOT%\\handoff\\out\\queued" mkdir "%ROOT%\\handoff\\out\\queued"',
  'set "Q=%ROOT%\\handoff\\out\\queued\\%R%"',
  'if exist "%Q%" rmdir /s /q "%Q%"',
  'move "%DR%" "%Q%" >nul',
  "echo agent.cmd: queued parcel for '%R%'",
  'exit /b 0',
  '',
  ':inbox',
  'set "SUB=%~1"',
  'if "%SUB%"=="" set "SUB=list"',
  'if /I "%SUB%"=="list" (',
  '  goto :inbox_list',
  ')',
  'if /I "%SUB%"=="ls" (',
  '  goto :inbox_list',
  ')',
  'goto :inbox_after_list',
  ':inbox_list',
  '  if not exist "%ROOT%\\handoff\\in\\received" ( echo (inbox empty) & exit /b 0 )',
  '  set "ANY="',
  '  for /d %%D in ("%ROOT%\\handoff\\in\\received\\*") do ( set "ANY=1" & echo %%~nxD )',
  '  if "!ANY!"=="" echo (inbox empty)',
  '  exit /b 0',
  ':inbox_after_list',
  'if /I "%SUB%"=="show" (',
  '  if "%~2"=="" ( echo agent.cmd: inbox show ^<parcel^> 1>&2 & exit /b 1 )',
  '  set "P=%ROOT%\\handoff\\in\\received\\%~2"',
  '  if not exist "!P!" ( echo agent.cmd: inbox: no parcel \'%~2\' 1>&2 & exit /b 1 )',
  '  if exist "!P!\\meta.yaml" findstr /R /C:"^userDirected: *true" "!P!\\meta.yaml" >nul && echo == user-directed work (host-stamped) ==',
  '  if exist "!P!\\README.md" ( echo == note == & type "!P!\\README.md" )',
  '  if exist "!P!\\squashed.diff" ( echo. & echo == diffstat == & git apply --stat "!P!\\squashed.diff" )',
  '  exit /b 0',
  ')',
  'if /I "%SUB%"=="done" (',
  '  if "%~2"=="" ( echo agent.cmd: inbox done ^<parcel^> 1>&2 & exit /b 1 )',
  '  set "P=%ROOT%\\handoff\\in\\received\\%~2"',
  '  if not exist "!P!" ( echo agent.cmd: inbox: no parcel \'%~2\' 1>&2 & exit /b 1 )',
  '  if not exist "%ROOT%\\handoff\\in\\processed" mkdir "%ROOT%\\handoff\\in\\processed"',
  '  set "DEST=%ROOT%\\handoff\\in\\processed\\%~2"',
  '  if exist "!DEST!" rmdir /s /q "!DEST!"',
  '  move "!P!" "!DEST!" >nul',
  "  echo agent.cmd: marked '%~2' processed",
  '  exit /b 0',
  ')',
  "echo agent.cmd: inbox: unknown subcommand '%SUB%' 1>&2 & exit /b 1",
  '',
  ':attest',
  'set "CMD="',
  'set "RESULT="',
  'set "SUMMARY="',
  ':at_loop',
  'if "%~1"=="" goto :at_done',
  'if /I "%~1"=="--command" ( set "CMD=%~2" & shift & shift & goto :at_loop )',
  'if /I "%~1"=="--result" ( set "RESULT=%~2" & shift & shift & goto :at_loop )',
  'if /I "%~1"=="--summary" ( set "SUMMARY=%~2" & shift & shift & goto :at_loop )',
  'echo agent.cmd: attest: unexpected arg %~1 1>&2 & exit /b 1',
  ':at_done',
  'if "%CMD%"=="" ( echo agent.cmd: attest: --command required 1>&2 & exit /b 1 )',
  'if /I not "%RESULT%"=="pass" if /I not "%RESULT%"=="fail" ( echo agent.cmd: attest: --result must be pass or fail 1>&2 & exit /b 1 )',
  'set "HEAD="',
  'for /f "delims=" %%H in (\'git -C "%ROOT%\\repo" rev-parse --short HEAD 2^>nul\') do set "HEAD=%%H"',
  'if "%HEAD%"=="" ( echo agent.cmd: attest: cannot read repo HEAD — commit your work first 1>&2 & exit /b 1 )',
  'set "ST=%ROOT%\\status.md"',
  '>>"%ST%" echo.',
  '>>"%ST%" echo ```quimby-attest',
  '>>"%ST%" echo command: %CMD%',
  '>>"%ST%" echo result: %RESULT%',
  'if not "%SUMMARY%"=="" >>"%ST%" echo summary: %SUMMARY%',
  '>>"%ST%" echo atCommit: %HEAD%',
  '>>"%ST%" echo ```',
  'echo agent.cmd: attested %RESULT% @ %HEAD%',
  'exit /b 0',
  '',
  ':peers',
  'if not "%~1"=="" (',
  '  if not exist "%ROOT%\\status\\%~1.md" ( echo agent.cmd: peers: no status mirror for \'%~1\' 1>&2 & exit /b 1 )',
  '  type "%ROOT%\\status\\%~1.md"',
  '  exit /b 0',
  ')',
  'if not exist "%ROOT%\\status" ( echo (no peers) & exit /b 0 )',
  'set "ANY="',
  'for %%F in ("%ROOT%\\status\\*.md") do ( set "ANY=1" & echo %%~nF )',
  'if "!ANY!"=="" echo (no peers)',
  'exit /b 0',
  '',
  ':usage',
  'echo agent.cmd — your Quimby coordination tool (mechanics only; judgment stays in instructions)',
  'echo.',
  'echo   assignment                                             show the current assignment',
  'echo   assignment set -m msg^|--file path^-                    replace the current assignment',
  'echo   status                                                 show your current status journal',
  'echo   status set^|append^|done -m msg^|--file path^-          update your status journal',
  'echo   handoff ^<recipient^> [-m msg] [--attach agent] [--draft]',
  'echo                                                           author + publish a parcel',
  'echo   delegate ^<recipient^> -m msg [--attach agent] [--draft] relay user-directed work',
  "echo   publish ^<recipient^>                                     publish a --draft'd parcel",
  'echo   inbox [list ^| show ^<p^> ^| done ^<p^>]                    list / read / process parcels',
  'echo   attest --command CMD --result pass^|fail [--summary S]   append a quimby-attest block',
  'echo   peers [name]                                            list peer status, or read one',
  'echo.',
  "echo Delivery across the boundary is the host's job (quimby dispatch / merge).",
  'exit /b 0',
]
