/**
 * `agent.sh` — the agent's own Quimby coordination tool. It is the *mechanical enactment* layer
 * under the CLAUDE.md conventions: the conventions keep every judgment call (whether/when to
 * send, what to record where, how to weigh a peer note), and this tool performs the fiddly,
 * silent-failure-prone steps reliably — the atomic author-then-publish move, the exact
 * `quimby-attest` block, the inbox `received → processed` lifecycle.
 *
 * It is a POSIX **shell** script, not a Node program, on purpose: it runs *inside* the
 * sandbox/remote, where quimby's guaranteed floor is `sh` + `git` + coreutils (git is already a
 * hard remote dependency) but Node is **not** — an Ollama/qwen runtime may have no Node, and the
 * whole point of cheap agents is that they work there. A shell tool adds zero new remote
 * dependency. DRY is preserved where it is fragile: the host is always the *parser* of these
 * formats (canonical TypeScript), the agent is only ever the *producer*, so there is no
 * duplicated parser to drift — only a producer/consumer contract, pinned by a round-trip test.
 *
 * The tool never crosses the boundary: carrying a parcel to a peer, or out to the user's repo,
 * stays the host's job (`quimby dispatch`/`merge`). `agent.sh` only ever writes the agent's
 * own workspace. And it is an *optimization* over the prose conventions, never a replacement — a
 * runtime without `sh` (or any agent lacking the script) still works by following CLAUDE.md.
 */
export const AGENT_SCRIPT_CMD_FILENAME = 'agent.cmd'

export const AGENT_SCRIPT_LEGACY_CMD_FILENAME = 'quimby-agent.cmd'

export const AGENT_SCRIPT_LEGACY_SH_FILENAME = 'quimby-agent.sh'

export const AGENT_SCRIPT_SH_FILENAME = 'agent.sh'

/**
 * The POSIX `sh` implementation — the canonical one, since every place `quimby-agent` actually
 * runs (Docker Sandbox, OpenShell, SSH to Linux/macOS) is POSIX. Deps: `sh` + `git` + coreutils.
 */
export function renderAgentScript(): string {
  return SH_LINES.join('\n') + '\n'
}

/**
 * The Windows `cmd` twin, for the one place `sh` is absent: a Windows-hosted local agent. Remote
 * sandboxes are POSIX, so this is a best-effort safety net — see {@link renderAgentScript} for the
 * canonical behavior. If it misbehaves, the CLAUDE.md prose conventions are the fallback. Deps:
 * `cmd` + `git`.
 */
export function renderAgentScriptCmd(): string {
  return CMD_LINES.join('\r\n') + '\r\n'
}

// Each line is a JS double-quoted string: sh `"` is escaped `\"`, sh `\` is escaped `\\` (so a
// shell `\n` reads as backslash-n for printf), backticks are literal. No `${...}` is used in the
// shell (guards replace parameter defaults), so nothing here interpolates.
const SH_LINES = [
  '#!/bin/sh',
  "# agent.sh — the agent's Quimby coordination tool: mechanical enactment of the assignment /",
  '# status / handoff / inbox / attest conventions. Judgment (whether/when to send, what to record) stays in CLAUDE.md; this',
  "# only performs the error-prone steps reliably. Deps: sh + git + coreutils (quimby's guaranteed",
  '# remote floor) — no node. If this tool is absent, the CLAUDE.md conventions are the fallback.',
  "# Carrying across the boundary is the host's job; this only ever writes your own workspace.",
  'set -eu',
  '',
  'qa_die() { echo "agent.sh: $1" >&2; exit 1; }',
  '',
  '# mkdir -p, but on failure name the most likely cause. A host-side `quimby rebuild` replaces',
  '# handoff/{in,out} under the guest mount, and a virtiofs/9p guest can keep a stale dentry: the',
  '# dir still lists (getdents) but stat returns ENOENT, so mkdir -p of a child fails. Dropping the',
  '# guest cache needs root, so this cannot self-heal — it points at the fix instead of dying blind.',
  'qa_mkdir() {',
  '  mkdir -p "$1" 2>/dev/null && return 0',
  '  echo "agent.sh: could not create \'$1\'." >&2',
  '  echo "agent.sh: if handoff/ lists but its entries stat as \'?\' or ENOENT, the guest is holding a" >&2',
  '  echo "  stale virtiofs dentry (common right after a host-side \'quimby rebuild\'). Drop it and retry:" >&2',
  '  echo "    sync; echo 2 | sudo tee /proc/sys/vm/drop_caches" >&2',
  '  exit 1',
  '}',
  '',
  '# The agent root is the nearest ancestor holding both handoff/ and assignment.md (present at the',
  '# agent root, never inside repo/), so the tool works from the agent dir or from within repo/.',
  'qa_root() {',
  '  d=$PWD',
  '  while [ "$d" != "/" ]; do',
  '    if [ -d "$d/handoff" ] && [ -f "$d/assignment.md" ]; then',
  '      printf \'%s\\n\' "$d"',
  '      return 0',
  '    fi',
  '    d=$(dirname "$d")',
  '  done',
  '  return 1',
  '}',
  '',
  '# Publish is the atomic author-then-publish move: a same-filesystem rename of the whole draft',
  '# dir into out/queued/, so a partial parcel never appears as queued (the race fix by construction).',
  'qa_publish() {',
  '  recipient=$1',
  '  draft="$ROOT/handoff/out/draft/$recipient"',
  '  [ -d "$draft" ] || qa_die "publish: no draft for \'$recipient\'"',
  '  qa_mkdir "$ROOT/handoff/out/queued"',
  '  queued="$ROOT/handoff/out/queued/$recipient"',
  '  rm -rf "$queued"',
  '  mv "$draft" "$queued"',
  '  echo "agent.sh: queued parcel for \'$recipient\' — quimby dispatch carries it (the server also auto-dispatches)"',
  '}',
  '',
  'qa_read_stdin() {',
  '  tmp=$(mktemp)',
  '  cat > "$tmp"',
  '  printf \'%s\\n\' "$tmp"',
  '}',
  '',
  'cmd_assignment() {',
  '  if [ $# -gt 0 ]; then sub=$1; shift; else sub=show; fi',
  '  case $sub in',
  '    show)',
  '      cat "$ROOT/assignment.md"',
  '      ;;',
  '    set)',
  "      message=''",
  "      file=''",
  '      while [ $# -gt 0 ]; do',
  '        case $1 in',
  '          -m|--message) shift; [ $# -gt 0 ] || qa_die "assignment set: -m needs text"; message=$1 ;;',
  '          --file) shift; [ $# -gt 0 ] || qa_die "assignment set: --file needs a path"; file=$1 ;;',
  '          -*) qa_die "assignment set: unknown option $1" ;;',
  '          *) qa_die "assignment set: unexpected arg $1" ;;',
  '        esac',
  '        shift',
  '      done',
  '      if [ -n "$file" ]; then',
  '        [ "$file" = "-" ] || [ -f "$file" ] || qa_die "assignment set: --file not found: $file"',
  '        if [ "$file" = "-" ]; then tmp=$(qa_read_stdin); mv "$tmp" "$ROOT/assignment.md"; else cp "$file" "$ROOT/assignment.md"; fi',
  '      else',
  '        [ -n "$message" ] || qa_die "assignment set: provide -m or --file"',
  '        printf \'%s\\n\' "$message" > "$ROOT/assignment.md"',
  '      fi',
  '      echo "agent.sh: assignment set"',
  '      ;;',
  '    *) qa_die "assignment: unknown subcommand \'$sub\' (show | set -m text | set --file path)" ;;',
  '  esac',
  '}',
  '',
  'cmd_status() {',
  '  if [ $# -gt 0 ]; then sub=$1; shift; else sub=show; fi',
  '  case $sub in',
  '    show)',
  '      cat "$ROOT/status.md"',
  '      ;;',
  '    set|append|done)',
  "      message=''",
  "      file=''",
  '      while [ $# -gt 0 ]; do',
  '        case $1 in',
  '          -m|--message) shift; [ $# -gt 0 ] || qa_die "status $sub: -m needs text"; message=$1 ;;',
  '          --file) shift; [ $# -gt 0 ] || qa_die "status $sub: --file needs a path"; file=$1 ;;',
  '          -*) qa_die "status $sub: unknown option $1" ;;',
  '          *) qa_die "status $sub: unexpected arg $1" ;;',
  '        esac',
  '        shift',
  '      done',
  '      if [ "$sub" = done ] && [ -z "$message" ] && [ -z "$file" ]; then message=done.; fi',
  '      if [ -n "$file" ]; then',
  '        [ "$file" = "-" ] || [ -f "$file" ] || qa_die "status $sub: --file not found: $file"',
  '        if [ "$file" = "-" ]; then src=$(qa_read_stdin); else src=$file; fi',
  '        if [ "$sub" = set ]; then cp "$src" "$ROOT/status.md"; else cat "$src" >> "$ROOT/status.md"; fi',
  '        [ "$file" = "-" ] && rm -f "$src"',
  '      else',
  '        [ -n "$message" ] || qa_die "status $sub: provide -m or --file"',
  '        if [ "$sub" = set ]; then printf \'%s\\n\' "$message" > "$ROOT/status.md"; else printf \'\\n%s\\n\' "$message" >> "$ROOT/status.md"; fi',
  '      fi',
  '      echo "agent.sh: status $sub"',
  '      ;;',
  '    *) qa_die "status: unknown subcommand \'$sub\' (show | set | append | done)" ;;',
  '  esac',
  '}',
  '',
  'cmd_handoff() {',
  '  mode=$1',
  '  shift',
  "  recipient=''",
  "  message=''",
  "  attach=''",
  '  publish=1',
  "  files=''",
  '  while [ $# -gt 0 ]; do',
  '    case $1 in',
  '      -m|--message) shift; [ $# -gt 0 ] || qa_die "handoff: -m needs a message"; message=$1 ;;',
  '      --attach) shift; [ $# -gt 0 ] || qa_die "handoff: --attach needs an agent"; attach=$1 ;;',
  '      --file) shift; [ $# -gt 0 ] || qa_die "handoff: --file needs a path"; files="$files $1" ;;',
  '      --draft) publish=0 ;;',
  '      -*) qa_die "handoff: unknown option $1" ;;',
  '      *) if [ -z "$recipient" ]; then recipient=$1; else qa_die "handoff: unexpected arg $1"; fi ;;',
  '    esac',
  '    shift',
  '  done',
  '  [ -n "$recipient" ] || qa_die "handoff: recipient required (handoff <recipient> [-m msg] [--attach agent] [--file path])"',
  '  case $recipient in',
  '    */*|.|..) qa_die "handoff: invalid recipient \'$recipient\'" ;;',
  '  esac',
  '  [ "$mode" != delegate ] || [ -n "$message" ] || qa_die "delegate: message required"',
  '  draft="$ROOT/handoff/out/draft/$recipient"',
  '  rm -rf "$draft"',
  '  qa_mkdir "$draft"',
  '  if [ "$mode" = delegate ]; then',
  "    printf '%s\\ndelegated: true\\n' '---' > \"$draft/README.md\"",
  '    [ -z "$attach" ] || printf \'attach: %s\\n\' "$attach" >> "$draft/README.md"',
  "    printf '%s\\n' '---' >> \"$draft/README.md\"",
  '    printf \'%s\\n\' "$message" >> "$draft/README.md"',
  '  elif [ -n "$attach" ]; then',
  // A leading '---' would be read as options by some printf implementations, so lead with %s.
  "    printf '%s\\nattach: %s\\n%s\\n' '---' \"$attach\" '---' > \"$draft/README.md\"",
  '    printf \'%s\\n\' "$message" >> "$draft/README.md"',
  '  else',
  '    printf \'%s\\n\' "$message" > "$draft/README.md"',
  '  fi',
  '  for f in $files; do',
  '    [ -f "$f" ] || qa_die "handoff: --file not found: $f"',
  '    cp "$f" "$draft/"',
  '  done',
  '  if [ "$publish" -eq 0 ]; then',
  '    echo "agent.sh: drafted parcel for \'$recipient\' (publish with: ./agent.sh publish $recipient)"',
  '    return 0',
  '  fi',
  '  qa_publish "$recipient"',
  '}',
  '',
  'cmd_inbox() {',
  '  if [ $# -gt 0 ]; then sub=$1; shift; else sub=list; fi',
  '  case $sub in',
  '    list|ls)',
  '      rcv="$ROOT/handoff/in/received"',
  '      [ -d "$rcv" ] || { echo \'(inbox empty)\'; return 0; }',
  '      found=0',
  '      for d in "$rcv"/*/; do',
  '        [ -d "$d" ] || continue',
  '        found=1',
  '        name=$(basename "$d")',
  "        head1='(no note)'",
  '        [ -f "$d/README.md" ] && head1=$(head -n 1 "$d/README.md")',
  "        tag=''",
  '        [ -f "$d/squashed.diff" ] && tag=\' [diff]\'',
  '        if [ -f "$d/meta.yaml" ] && grep -Eq \'^userDirected: *true\' "$d/meta.yaml"; then tag="$tag [user-directed]"; fi',
  '        printf \'%s%s — %s\\n\' "$name" "$tag" "$head1"',
  '      done',
  '      [ "$found" -eq 1 ] || echo \'(inbox empty)\'',
  '      ;;',
  '    show)',
  "      [ $# -gt 0 ] || qa_die 'inbox show <parcel>'",
  '      p="$ROOT/handoff/in/received/$1"',
  '      [ -d "$p" ] || qa_die "inbox: no parcel \'$1\'"',
  '      [ ! -f "$p/meta.yaml" ] || ! grep -Eq \'^userDirected: *true\' "$p/meta.yaml" || echo \'── user-directed work (host-stamped) ──\'',
  '      [ -f "$p/README.md" ] && { echo \'── note ──\'; cat "$p/README.md"; }',
  '      if [ -f "$p/squashed.diff" ]; then',
  "        echo ''",
  "        echo '── diffstat ──'",
  '        git apply --stat "$p/squashed.diff" 2>/dev/null || echo \'(unable to stat diff)\'',
  '      fi',
  '      ;;',
  '    done)',
  "      [ $# -gt 0 ] || qa_die 'inbox done <parcel>'",
  '      p="$ROOT/handoff/in/received/$1"',
  '      [ -d "$p" ] || qa_die "inbox: no parcel \'$1\'"',
  '      qa_mkdir "$ROOT/handoff/in/processed"',
  '      dest="$ROOT/handoff/in/processed/$1"',
  '      rm -rf "$dest"',
  '      mv "$p" "$dest"',
  '      echo "agent.sh: marked \'$1\' processed"',
  '      ;;',
  '    *) qa_die "inbox: unknown subcommand \'$sub\' (list | show <p> | done <p>)" ;;',
  '  esac',
  '}',
  '',
  '# attest formats the quimby-attest block the host parser expects and fills atCommit from the repo',
  "# HEAD, so the agent can't mis-key it or paste a wrong hash. The agent runs the check and states",
  "# the result; this only records it. A dirty tree is warned about — atCommit wouldn't cover it.",
  'cmd_attest() {',
  "  command=''",
  "  result=''",
  "  summary=''",
  '  while [ $# -gt 0 ]; do',
  '    case $1 in',
  '      --command) shift; [ $# -gt 0 ] || qa_die "attest: --command needs a value"; command=$1 ;;',
  '      --result) shift; [ $# -gt 0 ] || qa_die "attest: --result needs pass|fail"; result=$1 ;;',
  '      --summary) shift; [ $# -gt 0 ] || qa_die "attest: --summary needs a value"; summary=$1 ;;',
  '      -*) qa_die "attest: unknown option $1" ;;',
  '      *) qa_die "attest: unexpected arg $1" ;;',
  '    esac',
  '    shift',
  '  done',
  '  [ -n "$command" ] || qa_die "attest: --command required (the check you ran, e.g. \'npm run ci\')"',
  '  case $result in',
  '    pass|fail) ;;',
  "    *) qa_die 'attest: --result must be pass or fail' ;;",
  '  esac',
  '  repo="$ROOT/repo"',
  '  head=$(git -C "$repo" rev-parse --short HEAD 2>/dev/null) || qa_die \'attest: cannot read repo HEAD — commit your work first\'',
  '  if [ -n "$(git -C "$repo" status --porcelain 2>/dev/null)" ]; then',
  '    echo "agent.sh: WARNING uncommitted changes in repo — atCommit ($head) won\'t cover them; commit first, then re-attest" >&2',
  '  fi',
  '  status="$ROOT/status.md"',
  '  printf \'\\n```quimby-attest\\n\' >> "$status"',
  '  printf \'command: %s\\n\' "$command" >> "$status"',
  '  printf \'result: %s\\n\' "$result" >> "$status"',
  '  [ -n "$summary" ] && printf \'summary: %s\\n\' "$summary" >> "$status"',
  '  printf \'atCommit: %s\\n\' "$head" >> "$status"',
  '  printf \'```\\n\' >> "$status"',
  '  echo "agent.sh: attested $result @ $head"',
  '}',
  '',
  'cmd_peers() {',
  '  sdir="$ROOT/status"',
  '  if [ $# -gt 0 ]; then',
  '    f="$sdir/$1.md"',
  '    [ -f "$f" ] || qa_die "peers: no status mirror for \'$1\'"',
  '    cat "$f"',
  '    return 0',
  '  fi',
  '  [ -d "$sdir" ] || { echo \'(no peers)\'; return 0; }',
  '  found=0',
  '  for f in "$sdir"/*.md; do',
  '    [ -f "$f" ] || continue',
  '    found=1',
  '    basename "$f" .md',
  '  done',
  '  [ "$found" -eq 1 ] || echo \'(no peers)\'',
  '}',
  '',
  'usage() {',
  "  cat <<'EOF'",
  'agent.sh — your Quimby coordination tool (mechanics only; judgment stays in instructions)',
  '',
  '  assignment              show the current assignment',
  '  assignment set -m msg|--file path|-',
  '                          replace the current assignment',
  '  status                  show your current status journal',
  '  status set -m msg|--file path|-',
  '                          replace your status journal',
  '  status append -m msg|--file path|-',
  '                          append to your status journal',
  '  status done [-m msg|--file path|-]',
  '                          append a done summary (default: "done.")',
  '  handoff <recipient> [-m msg] [--attach agent] [--file path] [--draft]',
  '                        author + atomically publish a parcel to a peer',
  '  delegate <recipient> -m msg [--attach agent] [--file path] [--draft]',
  '                        relay user-directed work to a peer',
  '  publish <recipient>   publish a parcel you drafted with --draft',
  '  inbox [list]          list delivered parcels',
  "  inbox show <parcel>   print a parcel's note and diffstat",
  '  inbox done <parcel>   mark a parcel processed',
  '  attest --command CMD --result pass|fail [--summary S]',
  '                        append a quimby-attest block (atCommit auto-filled from HEAD)',
  '  peers [name]          list peer status mirrors, or read one',
  '',
  "Delivery across the boundary is the host's job (quimby dispatch / merge); this",
  'tool only ever writes your own workspace.',
  'EOF',
  '}',
  '',
  'main() {',
  '  [ $# -gt 0 ] || { usage; exit 0; }',
  '  verb=$1',
  '  shift',
  '  case $verb in',
  '    help|-h|--help) usage; exit 0 ;;',
  '  esac',
  '  ROOT=$(qa_root) || qa_die "not inside an agent workspace (no handoff/ + assignment.md above $PWD)"',
  '  case $verb in',
  '    handoff) cmd_handoff handoff "$@" ;;',
  '    delegate) cmd_handoff delegate "$@" ;;',
  '    publish) [ $# -gt 0 ] || qa_die \'publish <recipient>\'; qa_publish "$1" ;;',
  '    inbox) cmd_inbox "$@" ;;',
  '    attest) cmd_attest "$@" ;;',
  '    peers) cmd_peers "$@" ;;',
  '    assignment) cmd_assignment "$@" ;;',
  '    status) cmd_status "$@" ;;',
  '    *) qa_die "unknown command \'$verb\' — run: ./agent.sh help" ;;',
  '  esac',
  '}',
  '',
  'main "$@"',
]

// Windows batch twin. Each JS line escapes `"`→`\"` and `\`→`\\`; backticks are literal. cmd has
// no `${...}`/`\n` semantics, so only backslashes (Windows paths) need doubling. Best-effort and
// unverified on Windows — the .sh above is canonical; this exists only for a Windows-hosted agent.
const CMD_LINES = [
  '@echo off',
  'setlocal enabledelayedexpansion',
  'rem agent.cmd — Windows twin of agent.sh (that file is canonical). Best-effort:',
  'rem remote sandboxes are POSIX, so this only matters for a Windows-hosted agent. If it misbehaves,',
  'rem the CLAUDE.md prose conventions are the fallback. Deps: cmd + git.',
  '',
  'call :find_root',
  'if "%ROOT%"=="" ( echo agent.cmd: not inside an agent workspace 1>&2 & exit /b 1 )',
  '',
  'set "VERB=%~1"',
  'if "%VERB%"=="" goto :usage',
  'shift',
  'if /I "%VERB%"=="help" goto :usage',
  'if /I "%VERB%"=="assignment" goto :assignment',
  'if /I "%VERB%"=="status" goto :status',
  'if /I "%VERB%"=="handoff" ( set "DELEGATED=0" & goto :handoff )',
  'if /I "%VERB%"=="delegate" ( set "DELEGATED=1" & goto :handoff )',
  'if /I "%VERB%"=="publish" goto :publish_cmd',
  'if /I "%VERB%"=="inbox" goto :inbox',
  'if /I "%VERB%"=="attest" goto :attest',
  'if /I "%VERB%"=="peers" goto :peers',
  "echo agent.cmd: unknown command '%VERB%' — run: agent.cmd help 1>&2",
  'exit /b 1',
  '',
  ':find_root',
  'set "ROOT="',
  'set "D=%CD%"',
  ':fr_loop',
  'if exist "%D%\\handoff" if exist "%D%\\assignment.md" ( set "ROOT=%D%" & exit /b 0 )',
  'for %%P in ("%D%\\..") do set "PARENT=%%~fP"',
  'if "%PARENT%"=="%D%" exit /b 0',
  'set "D=%PARENT%"',
  'goto :fr_loop',
  '',
  ':assignment',
  'set "SUB=%~1"',
  'if "%SUB%"=="" set "SUB=show"',
  'if /I "%SUB%"=="show" ( type "%ROOT%\\assignment.md" & exit /b 0 )',
  'if /I not "%SUB%"=="set" ( echo agent.cmd: assignment: unknown subcommand %SUB% 1>&2 & exit /b 1 )',
  'shift',
  'set "MSG="',
  'set "FILE="',
  ':as_loop',
  'if "%~1"=="" goto :as_done',
  'if /I "%~1"=="-m" ( set "MSG=%~2" & shift & shift & goto :as_loop )',
  'if /I "%~1"=="--message" ( set "MSG=%~2" & shift & shift & goto :as_loop )',
  'if /I "%~1"=="--file" ( set "FILE=%~2" & shift & shift & goto :as_loop )',
  'echo agent.cmd: assignment set: unexpected arg %~1 1>&2 & exit /b 1',
  ':as_done',
  'if not "%FILE%"=="" (',
  '  if "%FILE%"=="-" ( more > "%ROOT%\\assignment.md" ) else ( if not exist "%FILE%" ( echo agent.cmd: assignment set: --file not found: %FILE% 1>&2 & exit /b 1 ) & copy /y "%FILE%" "%ROOT%\\assignment.md" >nul )',
  ') else (',
  '  if "%MSG%"=="" ( echo agent.cmd: assignment set: provide -m or --file 1>&2 & exit /b 1 )',
  '  >"%ROOT%\\assignment.md" echo(%MSG%',
  ')',
  'echo agent.cmd: assignment set',
  'exit /b 0',
  '',
  ':status',
  'set "SUB=%~1"',
  'if "%SUB%"=="" set "SUB=show"',
  'if /I "%SUB%"=="show" ( type "%ROOT%\\status.md" & exit /b 0 )',
  'if /I not "%SUB%"=="set" if /I not "%SUB%"=="append" if /I not "%SUB%"=="done" ( echo agent.cmd: status: unknown subcommand %SUB% 1>&2 & exit /b 1 )',
  'shift',
  'set "MSG="',
  'set "FILE="',
  ':st_loop',
  'if "%~1"=="" goto :st_done',
  'if /I "%~1"=="-m" ( set "MSG=%~2" & shift & shift & goto :st_loop )',
  'if /I "%~1"=="--message" ( set "MSG=%~2" & shift & shift & goto :st_loop )',
  'if /I "%~1"=="--file" ( set "FILE=%~2" & shift & shift & goto :st_loop )',
  'echo agent.cmd: status %SUB%: unexpected arg %~1 1>&2 & exit /b 1',
  ':st_done',
  'if /I "%SUB%"=="done" if "%MSG%"=="" if "%FILE%"=="" set "MSG=done."',
  'if not "%FILE%"=="" (',
  '  if "%FILE%"=="-" ( set "TMP=%TEMP%\\quimby-status-%RANDOM%.tmp" & more > "!TMP!" & set "FILE=!TMP!" )',
  '  if not exist "%FILE%" ( echo agent.cmd: status %SUB%: --file not found: %FILE% 1>&2 & exit /b 1 )',
  '  if /I "%SUB%"=="set" ( copy /y "%FILE%" "%ROOT%\\status.md" >nul ) else ( type "%FILE%" >> "%ROOT%\\status.md" )',
  '  if defined TMP del "!TMP!" >nul 2>nul',
  ') else (',
  '  if "%MSG%"=="" ( echo agent.cmd: status %SUB%: provide -m or --file 1>&2 & exit /b 1 )',
  '  if /I "%SUB%"=="set" ( >"%ROOT%\\status.md" echo(%MSG% ) else ( >>"%ROOT%\\status.md" echo. & >>"%ROOT%\\status.md" echo(%MSG% )',
  ')',
  'echo agent.cmd: status %SUB%',
  'exit /b 0',
  '',
  ':handoff',
  'set "RECIP="',
  'set "MSG="',
  'set "ATTACH="',
  'set "PUBLISH=1"',
  'set "FILES="',
  ':ho_loop',
  'if "%~1"=="" goto :ho_done',
  'if /I "%~1"=="-m" ( set "MSG=%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--message" ( set "MSG=%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--attach" ( set "ATTACH=%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--file" ( set FILES=!FILES! "%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--draft" ( set "PUBLISH=0" & shift & goto :ho_loop )',
  'if "!RECIP!"=="" ( set "RECIP=%~1" & shift & goto :ho_loop )',
  'echo agent.cmd: handoff: unexpected arg %~1 1>&2 & exit /b 1',
  ':ho_done',
  'if "%RECIP%"=="" ( echo agent.cmd: handoff: recipient required 1>&2 & exit /b 1 )',
  'if "%DELEGATED%"=="1" if "%MSG%"=="" ( echo agent.cmd: delegate: message required 1>&2 & exit /b 1 )',
  'set "DRAFT=%ROOT%\\handoff\\out\\draft\\%RECIP%"',
  'if exist "%DRAFT%" rmdir /s /q "%DRAFT%"',
  'mkdir "%DRAFT%" 2>nul',
  'if "%DELEGATED%"=="1" (',
  '  >"%DRAFT%\\README.md" echo ---',
  '  >>"%DRAFT%\\README.md" echo delegated: true',
  '  if not "%ATTACH%"=="" >>"%DRAFT%\\README.md" echo attach: %ATTACH%',
  '  >>"%DRAFT%\\README.md" echo ---',
  '  >>"%DRAFT%\\README.md" echo(%MSG%',
  ') else if not "%ATTACH%"=="" (',
  '  >"%DRAFT%\\README.md" echo ---',
  '  >>"%DRAFT%\\README.md" echo attach: %ATTACH%',
  '  >>"%DRAFT%\\README.md" echo ---',
  '  >>"%DRAFT%\\README.md" echo(%MSG%',
  ') else (',
  '  >"%DRAFT%\\README.md" echo(%MSG%',
  ')',
  'for %%F in (!FILES!) do if not "%%~F"=="" ( if not exist "%%~F" ( echo agent.cmd: handoff: --file not found: %%~F 1>&2 & exit /b 1 ) & copy /y "%%~F" "%DRAFT%\\" >nul )',
  'if "%PUBLISH%"=="0" ( echo agent.cmd: drafted parcel for \'%RECIP%\' & exit /b 0 )',
  'call :do_publish "%RECIP%"',
  'exit /b %ERRORLEVEL%',
  '',
  ':publish_cmd',
  'if "%~1"=="" ( echo agent.cmd: publish ^<recipient^> 1>&2 & exit /b 1 )',
  'call :do_publish "%~1"',
  'exit /b %ERRORLEVEL%',
  '',
  ':do_publish',
  'set "R=%~1"',
  'set "DR=%ROOT%\\handoff\\out\\draft\\%R%"',
  'if not exist "%DR%" ( echo agent.cmd: publish: no draft for \'%R%\' 1>&2 & exit /b 1 )',
  'if not exist "%ROOT%\\handoff\\out\\queued" mkdir "%ROOT%\\handoff\\out\\queued"',
  'set "Q=%ROOT%\\handoff\\out\\queued\\%R%"',
  'if exist "%Q%" rmdir /s /q "%Q%"',
  'move "%DR%" "%Q%" >nul',
  "echo agent.cmd: queued parcel for '%R%'",
  'exit /b 0',
  '',
  ':inbox',
  'set "SUB=%~1"',
  'if "%SUB%"=="" set "SUB=list"',
  'if /I "%SUB%"=="list" (',
  '  goto :inbox_list',
  ')',
  'if /I "%SUB%"=="ls" (',
  '  goto :inbox_list',
  ')',
  'goto :inbox_after_list',
  ':inbox_list',
  '  if not exist "%ROOT%\\handoff\\in\\received" ( echo (inbox empty) & exit /b 0 )',
  '  set "ANY="',
  '  for /d %%D in ("%ROOT%\\handoff\\in\\received\\*") do ( set "ANY=1" & echo %%~nxD )',
  '  if "!ANY!"=="" echo (inbox empty)',
  '  exit /b 0',
  ':inbox_after_list',
  'if /I "%SUB%"=="show" (',
  '  if "%~2"=="" ( echo agent.cmd: inbox show ^<parcel^> 1>&2 & exit /b 1 )',
  '  set "P=%ROOT%\\handoff\\in\\received\\%~2"',
  '  if not exist "!P!" ( echo agent.cmd: inbox: no parcel \'%~2\' 1>&2 & exit /b 1 )',
  '  if exist "!P!\\meta.yaml" findstr /R /C:"^userDirected: *true" "!P!\\meta.yaml" >nul && echo == user-directed work (host-stamped) ==',
  '  if exist "!P!\\README.md" ( echo == note == & type "!P!\\README.md" )',
  '  if exist "!P!\\squashed.diff" ( echo. & echo == diffstat == & git apply --stat "!P!\\squashed.diff" )',
  '  exit /b 0',
  ')',
  'if /I "%SUB%"=="done" (',
  '  if "%~2"=="" ( echo agent.cmd: inbox done ^<parcel^> 1>&2 & exit /b 1 )',
  '  set "P=%ROOT%\\handoff\\in\\received\\%~2"',
  '  if not exist "!P!" ( echo agent.cmd: inbox: no parcel \'%~2\' 1>&2 & exit /b 1 )',
  '  if not exist "%ROOT%\\handoff\\in\\processed" mkdir "%ROOT%\\handoff\\in\\processed"',
  '  set "DEST=%ROOT%\\handoff\\in\\processed\\%~2"',
  '  if exist "!DEST!" rmdir /s /q "!DEST!"',
  '  move "!P!" "!DEST!" >nul',
  "  echo agent.cmd: marked '%~2' processed",
  '  exit /b 0',
  ')',
  "echo agent.cmd: inbox: unknown subcommand '%SUB%' 1>&2 & exit /b 1",
  '',
  ':attest',
  'set "CMD="',
  'set "RESULT="',
  'set "SUMMARY="',
  ':at_loop',
  'if "%~1"=="" goto :at_done',
  'if /I "%~1"=="--command" ( set "CMD=%~2" & shift & shift & goto :at_loop )',
  'if /I "%~1"=="--result" ( set "RESULT=%~2" & shift & shift & goto :at_loop )',
  'if /I "%~1"=="--summary" ( set "SUMMARY=%~2" & shift & shift & goto :at_loop )',
  'echo agent.cmd: attest: unexpected arg %~1 1>&2 & exit /b 1',
  ':at_done',
  'if "%CMD%"=="" ( echo agent.cmd: attest: --command required 1>&2 & exit /b 1 )',
  'if /I not "%RESULT%"=="pass" if /I not "%RESULT%"=="fail" ( echo agent.cmd: attest: --result must be pass or fail 1>&2 & exit /b 1 )',
  'set "HEAD="',
  'for /f "delims=" %%H in (\'git -C "%ROOT%\\repo" rev-parse --short HEAD 2^>nul\') do set "HEAD=%%H"',
  'if "%HEAD%"=="" ( echo agent.cmd: attest: cannot read repo HEAD — commit your work first 1>&2 & exit /b 1 )',
  'set "ST=%ROOT%\\status.md"',
  '>>"%ST%" echo.',
  '>>"%ST%" echo ```quimby-attest',
  '>>"%ST%" echo command: %CMD%',
  '>>"%ST%" echo result: %RESULT%',
  'if not "%SUMMARY%"=="" >>"%ST%" echo summary: %SUMMARY%',
  '>>"%ST%" echo atCommit: %HEAD%',
  '>>"%ST%" echo ```',
  'echo agent.cmd: attested %RESULT% @ %HEAD%',
  'exit /b 0',
  '',
  ':peers',
  'if not "%~1"=="" (',
  '  if not exist "%ROOT%\\status\\%~1.md" ( echo agent.cmd: peers: no status mirror for \'%~1\' 1>&2 & exit /b 1 )',
  '  type "%ROOT%\\status\\%~1.md"',
  '  exit /b 0',
  ')',
  'if not exist "%ROOT%\\status" ( echo (no peers) & exit /b 0 )',
  'set "ANY="',
  'for %%F in ("%ROOT%\\status\\*.md") do ( set "ANY=1" & echo %%~nF )',
  'if "!ANY!"=="" echo (no peers)',
  'exit /b 0',
  '',
  ':usage',
  'echo agent.cmd — your Quimby coordination tool (mechanics only; judgment stays in instructions)',
  'echo.',
  'echo   assignment                                             show the current assignment',
  'echo   assignment set -m msg^|--file path^-                    replace the current assignment',
  'echo   status                                                 show your current status journal',
  'echo   status set^|append^|done -m msg^|--file path^-          update your status journal',
  'echo   handoff ^<recipient^> [-m msg] [--attach agent] [--draft]',
  'echo                                                           author + publish a parcel',
  'echo   delegate ^<recipient^> -m msg [--attach agent] [--draft] relay user-directed work',
  "echo   publish ^<recipient^>                                     publish a --draft'd parcel",
  'echo   inbox [list ^| show ^<p^> ^| done ^<p^>]                    list / read / process parcels',
  'echo   attest --command CMD --result pass^|fail [--summary S]   append a quimby-attest block',
  'echo   peers [name]                                            list peer status, or read one',
  'echo.',
  "echo Delivery across the boundary is the host's job (quimby dispatch / merge).",
  'exit /b 0',
]
