/**
 * `agent.sh` — the agent's own Quimby coordination tool. It is the *mechanical enactment* layer
 * under the CLAUDE.md conventions: the conventions keep every judgment call (whether/when to
 * send, what to record where, how to weigh a peer note), and this tool performs the fiddly,
 * silent-failure-prone steps reliably — the atomic author-then-publish move, the exact
 * `quimby-attest` block, the inbox `received → processed` lifecycle.
 *
 * It is a POSIX **shell** script, not a Node program, on purpose: it runs *inside* the
 * sandbox/remote, where quimby's guaranteed floor is `sh` + `git` + coreutils (git is already a
 * hard remote dependency) but Node is **not** — an Ollama/qwen runtime may have no Node, and the
 * whole point of cheap agents is that they work there. A shell tool adds zero new remote
 * dependency. DRY is preserved where it is fragile: the host is always the *parser* of these
 * formats (canonical TypeScript), the agent is only ever the *producer*, so there is no
 * duplicated parser to drift — only a producer/consumer contract, pinned by a round-trip test.
 *
 * The tool never crosses the boundary: carrying a parcel to a peer, or out to the user's repo,
 * stays the host's job (`quimby dispatch`/`merge`). `agent.sh` only ever writes the agent's
 * own workspace. And it is an *optimization* over the prose conventions, never a replacement — a
 * runtime without `sh` (or any agent lacking the script) still works by following CLAUDE.md.
 */
export const AGENT_SCRIPT_CMD_FILENAME = 'agent.cmd'

export const AGENT_SCRIPT_LEGACY_CMD_FILENAME = 'quimby-agent.cmd'

export const AGENT_SCRIPT_LEGACY_SH_FILENAME = 'quimby-agent.sh'

export const AGENT_SCRIPT_SH_FILENAME = 'agent.sh'

/**
 * The coordination graph baked into the generated tool, resolved by the caller (which holds the
 * state) exactly like the `{{coordination}}` clause in the agent's instructions.
 */
export interface AgentScriptGraph {
  /** Every OTHER current agent — who this one may address at all. */
  roster?: readonly string[]
  /** Who this one may escalate to, already `@role`-expanded. */
  escalatesTo?: readonly string[]
}

/**
 * The POSIX `sh` implementation — the canonical one, since every place `quimby-agent` actually
 * runs (Docker Sandbox, OpenShell, SSH to Linux/macOS) is POSIX. Deps: `sh` + `git` + coreutils.
 */
export function renderAgentScript(graph: Readonly<AgentScriptGraph> = {}): string {
  return applyGraph(SH_LINES.join('\n') + '\n', graph)
}

/**
 * The Windows `cmd` twin, for the one place `sh` is absent: a Windows-hosted local agent. Remote
 * sandboxes are POSIX, so this is a best-effort safety net — see {@link renderAgentScript} for the
 * canonical behavior. If it misbehaves, the CLAUDE.md prose conventions are the fallback. Deps:
 * `cmd` + `git`.
 */
export function renderAgentScriptCmd(graph: Readonly<AgentScriptGraph> = {}): string {
  return applyGraph(CMD_LINES.join('\r\n') + '\r\n', graph)
}

// Substitute the resolved graph into the rendered script. Names are roster-validated upstream
// (`[A-Za-z0-9_-]`), but this filters anyway: a name carrying a quote or space would otherwise
// break out of the single-quoted shell assignment it lands in.
function applyGraph(script: string, graph: Readonly<AgentScriptGraph>): string {
  // `roster` is what every caller resolves (via resolveAgentGraph), so its presence — not its
  // emptiness — is the signal that a graph was rendered. A lone agent legitimately has an empty
  // roster and must still refuse every recipient.
  return script
    .replaceAll('{{graph}}', graph.roster === undefined ? '' : '1')
    .replaceAll('{{roster}}', safeNames(graph.roster))
    .replaceAll('{{escalate}}', safeNames(graph.escalatesTo))
}

function safeNames(names: readonly string[] | undefined): string {
  return (names ?? []).filter((name) => /^[A-Za-z0-9_-]+$/.test(name)).join(' ')
}

// Each line is a JS double-quoted string: sh `"` is escaped `\"`, sh `\` is escaped `\\` (so a
// shell `\n` reads as backslash-n for printf), backticks are literal. No `${...}` is used in the
// shell (guards replace parameter defaults), so nothing here interpolates.
const SH_LINES = [
  '#!/bin/sh',
  "# agent.sh — the agent's Quimby coordination tool: mechanical enactment of the assignment /",
  '# status / handoff / inbox / attest conventions. Judgment (whether/when to send, what to record) stays in CLAUDE.md; this',
  "# only performs the error-prone steps reliably. Deps: sh + git + coreutils (quimby's guaranteed",
  '# remote floor) — no node. If this tool is absent, the CLAUDE.md conventions are the fallback.',
  "# Carrying across the boundary is the host's job; this only ever writes your own workspace.",
  'set -eu',
  '',
  'qa_die() { echo "agent.sh: $1" >&2; exit 1; }',
  '',
  '# The coordination graph, resolved by the host and baked in here — refreshed on every launch and',
  '# every `quimby sync`, exactly like the CLAUDE.md coordination clause. Without it this tool could',
  '# only check that a recipient is non-empty, so addressing a removed agent published happily and',
  '# then bounced host-side, where the sender never sees it: the parcel sits in out/queued forever',
  '# and (bounces being attempt-once) stops even warning. Checking here is the only place the sender',
  '# learns. QA_ROSTER = every other current agent; QA_ESCALATE = who this one may summon.',
  '# QA_GRAPH marks that a graph was rendered AT ALL. Without it an empty QA_ESCALATE is ambiguous',
  '# — "the host told us nothing" (an old or ungraphed script, where blocking would be wrong) versus',
  '# "you genuinely have no escalation target" (where saying so is the whole point). Every check',
  '# below is gated on it, so a tool rendered without a graph behaves exactly as it did before.',
  "QA_GRAPH='{{graph}}'",
  "QA_ROSTER='{{roster}}'",
  "QA_ESCALATE='{{escalate}}'",
  '',
  '# Is $1 in the space-separated list $2? Callers gate on QA_GRAPH first, so reaching here with an',
  '# empty list means the host really said "nobody" — which must MISS, not pass.',
  'qa_in_list() {',
  '  [ -n "$2" ] || return 1',
  '  for qa_n in $2; do',
  '    [ "$qa_n" = "$1" ] && return 0',
  '  done',
  '  return 1',
  '}',
  '',
  '# mkdir -p, but on failure name the most likely cause. A host-side `quimby rebuild` replaces',
  '# handoff/{in,out} under the guest mount, and a virtiofs/9p guest can keep a stale dentry: the',
  '# dir still lists (getdents) but stat returns ENOENT, so mkdir -p of a child fails. Dropping the',
  '# guest cache needs root, so this cannot self-heal — it points at the fix instead of dying blind.',
  'qa_mkdir() {',
  '  mkdir -p "$1" 2>/dev/null && return 0',
  '  echo "agent.sh: could not create \'$1\'." >&2',
  '  echo "agent.sh: if handoff/ lists but its entries stat as \'?\' or ENOENT, the guest is holding a" >&2',
  '  echo "  stale virtiofs dentry (common right after a host-side \'quimby rebuild\'). Drop it and retry:" >&2',
  '  echo "    sync; echo 2 | sudo tee /proc/sys/vm/drop_caches" >&2',
  '  exit 1',
  '}',
  '',
  '# Close the guest bind-mount cache-lag window (same virtiofs/9p class as qa_mkdir): a courier',
  '# nudge naming a parcel can arrive before the just-delivered parcel is visible on this side, so',
  '# poll for the dir a few times before declaring it truly missing. QA_INBOX_RETRIES tunes the count',
  '# (default 3 ≈ 2s of 1s sleeps); the transient-vs-loss line is drawn at the retry boundary.',
  'qa_await_dir() {',
  '  set +u; tries=$QA_INBOX_RETRIES; set -u',
  '  [ -n "$tries" ] || tries=3',
  '  i=1',
  '  while :; do',
  '    [ -d "$1" ] && return 0',
  '    [ "$i" -ge "$tries" ] && return 1',
  '    i=$((i + 1))',
  '    sleep 1',
  '  done',
  '}',
  '',
  '# The agent root is the nearest ancestor holding both handoff/ and assignment.md (present at the',
  '# agent root, never inside repo/), so the tool works from the agent dir or from within repo/.',
  'qa_root() {',
  '  d=$PWD',
  '  while [ "$d" != "/" ]; do',
  '    if [ -d "$d/handoff" ] && [ -f "$d/assignment.md" ]; then',
  '      printf \'%s\\n\' "$d"',
  '      return 0',
  '    fi',
  '    d=$(dirname "$d")',
  '  done',
  '  return 1',
  '}',
  '',
  '# Publish is the atomic author-then-publish move: a same-filesystem rename of the whole draft',
  '# dir into out/queued/, so a partial parcel never appears as queued (the race fix by construction).',
  'qa_publish() {',
  '  recipient=$1',
  '  draft="$ROOT/handoff/out/draft/$recipient"',
  '  [ -d "$draft" ] || qa_die "publish: no draft for \'$recipient\'"',
  '  qa_mkdir "$ROOT/handoff/out/queued"',
  '  queued="$ROOT/handoff/out/queued/$recipient"',
  '  rm -rf "$queued"',
  '  mv "$draft" "$queued"',
  '  echo "agent.sh: queued parcel for \'$recipient\' — quimby dispatch carries it (the server also auto-dispatches)"',
  '}',
  '',
  'qa_read_stdin() {',
  '  tmp=$(mktemp)',
  '  cat > "$tmp"',
  '  printf \'%s\\n\' "$tmp"',
  '}',
  '',
  'cmd_assignment() {',
  '  if [ $# -gt 0 ]; then sub=$1; shift; else sub=show; fi',
  '  case $sub in',
  '    show)',
  '      cat "$ROOT/assignment.md"',
  '      ;;',
  '    set)',
  "      message=''",
  "      file=''",
  '      while [ $# -gt 0 ]; do',
  '        case $1 in',
  '          -m|--message) shift; [ $# -gt 0 ] || qa_die "assignment set: -m needs text"; message=$1 ;;',
  '          --file) shift; [ $# -gt 0 ] || qa_die "assignment set: --file needs a path"; file=$1 ;;',
  '          -*) qa_die "assignment set: unknown option $1" ;;',
  '          *) qa_die "assignment set: unexpected arg $1" ;;',
  '        esac',
  '        shift',
  '      done',
  '      if [ -n "$file" ]; then',
  '        [ "$file" = "-" ] || [ -f "$file" ] || qa_die "assignment set: --file not found: $file"',
  '        if [ "$file" = "-" ]; then tmp=$(qa_read_stdin); mv "$tmp" "$ROOT/assignment.md"; else cp "$file" "$ROOT/assignment.md"; fi',
  '      else',
  '        [ -n "$message" ] || qa_die "assignment set: provide -m or --file"',
  '        printf \'%s\\n\' "$message" > "$ROOT/assignment.md"',
  '      fi',
  '      echo "agent.sh: assignment set"',
  '      ;;',
  '    *) qa_die "assignment: unknown subcommand \'$sub\' (show | set -m text | set --file path)" ;;',
  '  esac',
  '}',
  '',
  'cmd_status() {',
  '  if [ $# -gt 0 ]; then sub=$1; shift; else sub=show; fi',
  '  case $sub in',
  '    show)',
  '      cat "$ROOT/status.md"',
  '      ;;',
  '    set|append|done)',
  "      message=''",
  "      file=''",
  '      while [ $# -gt 0 ]; do',
  '        case $1 in',
  '          -m|--message) shift; [ $# -gt 0 ] || qa_die "status $sub: -m needs text"; message=$1 ;;',
  '          --file) shift; [ $# -gt 0 ] || qa_die "status $sub: --file needs a path"; file=$1 ;;',
  '          -*) qa_die "status $sub: unknown option $1" ;;',
  '          *) qa_die "status $sub: unexpected arg $1" ;;',
  '        esac',
  '        shift',
  '      done',
  '      if [ "$sub" = done ] && [ -z "$message" ] && [ -z "$file" ]; then message=done.; fi',
  '      if [ -n "$file" ]; then',
  '        [ "$file" = "-" ] || [ -f "$file" ] || qa_die "status $sub: --file not found: $file"',
  '        if [ "$file" = "-" ]; then src=$(qa_read_stdin); else src=$file; fi',
  '        if [ "$sub" = set ]; then cp "$src" "$ROOT/status.md"; else cat "$src" >> "$ROOT/status.md"; fi',
  '        [ "$file" = "-" ] && rm -f "$src"',
  '      else',
  '        [ -n "$message" ] || qa_die "status $sub: provide -m or --file"',
  '        if [ "$sub" = set ]; then printf \'%s\\n\' "$message" > "$ROOT/status.md"; else printf \'\\n%s\\n\' "$message" >> "$ROOT/status.md"; fi',
  '      fi',
  '      echo "agent.sh: status $sub"',
  '      ;;',
  '    *) qa_die "status: unknown subcommand \'$sub\' (show | set | append | done)" ;;',
  '  esac',
  '}',
  '',
  'cmd_handoff() {',
  '  mode=$1',
  '  shift',
  "  recipient=''",
  "  message=''",
  "  attach=''",
  "  replyto=''",
  '  publish=1',
  "  files=''",
  '  while [ $# -gt 0 ]; do',
  '    case $1 in',
  '      -m|--message) shift; [ $# -gt 0 ] || qa_die "handoff: -m needs a message"; message=$1 ;;',
  '      --attach) shift; [ $# -gt 0 ] || qa_die "handoff: --attach needs an agent"; attach=$1 ;;',
  '      --to) shift; [ $# -gt 0 ] || qa_die "reply: --to needs a parcel name"; replyto=$1 ;;',
  '      --file) shift; [ $# -gt 0 ] || qa_die "handoff: --file needs a path"; files="$files $1" ;;',
  '      --draft) publish=0 ;;',
  '      -*) qa_die "handoff: unknown option $1" ;;',
  '      *) if [ -z "$recipient" ]; then recipient=$1; else qa_die "handoff: unexpected arg $1"; fi ;;',
  '    esac',
  '    shift',
  '  done',
  '  [ -n "$recipient" ] || qa_die "handoff: recipient required (handoff <recipient> [-m msg] [--attach agent] [--file path])"',
  '  case $recipient in',
  '    */*|.|..) qa_die "handoff: invalid recipient \'$recipient\'" ;;',
  '  esac',
  '  # Refuse an address that cannot be delivered, rather than queueing a parcel that bounces where',
  '  # only the host sees it. Named the same way `reply --to` refuses an unknown parcel.',
  '  if [ -n "$QA_GRAPH" ] && ! qa_in_list "$recipient" "$QA_ROSTER"; then',
  '    printf \'agent.sh: %s: "%s" is not an agent.\\n\' "$mode" "$recipient" >&2',
  '    printf \'  roster: %s\\n\' "$QA_ROSTER" >&2',
  '    qa_die "$mode: address one of those (the roster refreshes on launch and on quimby sync)"',
  '  fi',
  '  # An --attach naming no agent fails host-side as a FAILED carry, which retries every cycle —',
  '  # so it warns forever rather than once. Cheaper to refuse here.',
  '  if [ -n "$QA_GRAPH" ] && [ -n "$attach" ] && ! qa_in_list "$attach" "$QA_ROSTER"; then',
  '    printf \'agent.sh: %s: --attach "%s" is not an agent.\\n\' "$mode" "$attach" >&2',
  '    printf \'  roster: %s\\n\' "$QA_ROSTER" >&2',
  '    qa_die "$mode: attach one of those, or drop --attach to send your own work"',
  '  fi',
  '  # An escalation aimed outside the permitted set is silently normalized to an ordinary advisory',
  '  # by the host — delivered, but waking nobody. That silence is the whole failure, so name it.',
  '  if [ -n "$QA_GRAPH" ] && [ "$mode" = escalate ]; then',
  '    if [ -z "$QA_ESCALATE" ]; then',
  "      printf 'agent.sh: escalate: you have no escalation target.\\n' >&2",
  '      qa_die "escalate: everything you send is advisory — use handoff, or record it with status"',
  '    fi',
  '    if ! qa_in_list "$recipient" "$QA_ESCALATE"; then',
  '      printf \'agent.sh: escalate: you may not escalate to "%s".\\n\' "$recipient" >&2',
  '      printf \'  permitted: %s\\n\' "$QA_ESCALATE" >&2',
  '      qa_die "escalate: name exactly one of those (an unpermitted escalation wakes nobody)"',
  '    fi',
  '  fi',
  '  [ "$mode" != delegate ] || [ -n "$message" ] || qa_die "delegate: message required"',
  '  [ "$mode" != reply ] || [ -n "$replyto" ] || qa_die "reply: --to <parcel> required (the question you are answering)"',
  '  # Fail here, not silently at the host: the reply-interrupt is honored only if the named parcel',
  '  # really reached this inbox, so a wrong name would publish fine and then wake nobody.',
  '  if [ "$mode" = reply ] && [ ! -d "$ROOT/handoff/in/received/$replyto" ] \\',
  '     && [ ! -d "$ROOT/handoff/in/processed/$replyto" ] \\',
  '     && ! grep -qxF "$replyto" "$ROOT/handoff/in/processed.ledger" 2>/dev/null; then',
  '    printf \'agent.sh: reply: "%s" is not a parcel you received.\\n\' "$replyto" >&2',
  "    printf 'Your inbox holds:\\n' >&2",
  '    ls -1 "$ROOT/handoff/in/received" 2>/dev/null | sed \'s/^/  /\' >&2 || true',
  '    qa_die "reply: use one of those names, or send an ordinary handoff instead"',
  '  fi',
  '  # The interrupt-intent tag by verb; the host validates it against the directs graph (§6).',
  "  fm=''",
  '  case $mode in',
  "    delegate) fm='delegated: true' ;;",
  "    escalate) fm='escalate: true' ;;",
  "    ask) fm='expects-reply: true' ;;",
  '    reply) fm="reply-to: $replyto" ;;',
  '  esac',
  '  draft="$ROOT/handoff/out/draft/$recipient"',
  '  rm -rf "$draft"',
  '  qa_mkdir "$draft"',
  // A leading '---' would be read as options by some printf implementations, so lead with %s.
  '  if [ -n "$fm" ] || [ -n "$attach" ]; then',
  "    printf '%s\\n' '---' > \"$draft/README.md\"",
  '    [ -z "$fm" ] || printf \'%s\\n\' "$fm" >> "$draft/README.md"',
  '    [ -z "$attach" ] || printf \'attach: %s\\n\' "$attach" >> "$draft/README.md"',
  "    printf '%s\\n' '---' >> \"$draft/README.md\"",
  '    printf \'%s\\n\' "$message" >> "$draft/README.md"',
  '  else',
  '    printf \'%s\\n\' "$message" > "$draft/README.md"',
  '  fi',
  '  for f in $files; do',
  '    [ -f "$f" ] || qa_die "handoff: --file not found: $f"',
  '    cp "$f" "$draft/"',
  '  done',
  '  if [ "$publish" -eq 0 ]; then',
  '    echo "agent.sh: drafted parcel for \'$recipient\' (publish with: ./agent.sh publish $recipient)"',
  '    return 0',
  '  fi',
  '  qa_publish "$recipient"',
  '}',
  '',
  'cmd_inbox() {',
  '  if [ $# -gt 0 ]; then sub=$1; shift; else sub=list; fi',
  '  case $sub in',
  '    list|ls)',
  '      rcv="$ROOT/handoff/in/received"',
  '      [ -d "$rcv" ] || { echo \'(inbox empty)\'; return 0; }',
  '      found=0',
  '      for d in "$rcv"/*/; do',
  '        [ -d "$d" ] || continue',
  '        found=1',
  '        name=$(basename "$d")',
  "        head1='(no note)'",
  '        [ -f "$d/README.md" ] && head1=$(head -n 1 "$d/README.md")',
  "        tag=''",
  '        [ -f "$d/squashed.diff" ] && tag=\' [diff]\'',
  '        if [ -f "$d/meta.yaml" ] && grep -Eq \'^userDirected: *true\' "$d/meta.yaml"; then tag="$tag [user-directed]"; fi',
  '        printf \'%s%s — %s\\n\' "$name" "$tag" "$head1"',
  '      done',
  '      [ "$found" -eq 1 ] || echo \'(inbox empty)\'',
  '      ;;',
  '    show)',
  "      [ $# -gt 0 ] || qa_die 'inbox show <parcel>'",
  '      p="$ROOT/handoff/in/received/$1"',
  '      qa_await_dir "$p" || qa_die "inbox: parcel \'$1\' announced but not landed (retried — a mount-sync lag or a stale name). Run \'./agent.sh inbox\' to see what did arrive, or ask the sender to resend."',
  '      [ ! -f "$p/meta.yaml" ] || ! grep -Eq \'^userDirected: *true\' "$p/meta.yaml" || echo \'── user-directed work (host-stamped) ──\'',
  '      [ -f "$p/README.md" ] && { echo \'── note ──\'; cat "$p/README.md"; }',
  '      if [ -f "$p/squashed.diff" ]; then',
  "        echo ''",
  "        echo '── diffstat ──'",
  '        git apply --stat "$p/squashed.diff" 2>/dev/null || echo \'(unable to stat diff)\'',
  '      fi',
  '      ;;',
  '    done)',
  "      [ $# -gt 0 ] || qa_die 'inbox done <parcel>'",
  '      p="$ROOT/handoff/in/received/$1"',
  '      qa_await_dir "$p" || qa_die "inbox: no parcel \'$1\'"',
  '      qa_mkdir "$ROOT/handoff/in/processed"',
  '      dest="$ROOT/handoff/in/processed/$1"',
  '      rm -rf "$dest"',
  '      mv "$p" "$dest"',
  '      echo "agent.sh: marked \'$1\' processed"',
  '      ;;',
  '    *) qa_die "inbox: unknown subcommand \'$sub\' (list | show <p> | done <p>)" ;;',
  '  esac',
  '}',
  '',
  '# attest formats the quimby-attest block the host parser expects and fills atCommit from the repo',
  "# HEAD, so the agent can't mis-key it or paste a wrong hash. The agent runs the check and states",
  "# the result; this only records it. A dirty tree is warned about — atCommit wouldn't cover it.",
  'cmd_attest() {',
  "  command=''",
  "  result=''",
  "  summary=''",
  '  while [ $# -gt 0 ]; do',
  '    case $1 in',
  '      --command) shift; [ $# -gt 0 ] || qa_die "attest: --command needs a value"; command=$1 ;;',
  '      --result) shift; [ $# -gt 0 ] || qa_die "attest: --result needs pass|fail"; result=$1 ;;',
  '      --summary) shift; [ $# -gt 0 ] || qa_die "attest: --summary needs a value"; summary=$1 ;;',
  '      -*) qa_die "attest: unknown option $1" ;;',
  '      *) qa_die "attest: unexpected arg $1" ;;',
  '    esac',
  '    shift',
  '  done',
  '  [ -n "$command" ] || qa_die "attest: --command required (the check you ran, e.g. \'npm run ci\')"',
  '  case $result in',
  '    pass|fail) ;;',
  "    *) qa_die 'attest: --result must be pass or fail' ;;",
  '  esac',
  '  repo="$ROOT/repo"',
  '  head=$(git -C "$repo" rev-parse --short HEAD 2>/dev/null) || qa_die \'attest: cannot read repo HEAD — commit your work first\'',
  '  if [ -n "$(git -C "$repo" status --porcelain 2>/dev/null)" ]; then',
  '    echo "agent.sh: WARNING uncommitted changes in repo — atCommit ($head) won\'t cover them; commit first, then re-attest" >&2',
  '  fi',
  '  status="$ROOT/status.md"',
  '  printf \'\\n```quimby-attest\\n\' >> "$status"',
  '  printf \'command: %s\\n\' "$command" >> "$status"',
  '  printf \'result: %s\\n\' "$result" >> "$status"',
  '  [ -n "$summary" ] && printf \'summary: %s\\n\' "$summary" >> "$status"',
  '  printf \'atCommit: %s\\n\' "$head" >> "$status"',
  '  printf \'```\\n\' >> "$status"',
  '  echo "agent.sh: attested $result @ $head"',
  '}',
  '',
  'cmd_peers() {',
  '  sdir="$ROOT/status"',
  '  if [ $# -gt 0 ]; then',
  '    f="$sdir/$1.md"',
  '    [ -f "$f" ] || qa_die "peers: no status mirror for \'$1\'"',
  '    cat "$f"',
  '    return 0',
  '  fi',
  '  [ -d "$sdir" ] || { echo \'(no peers)\'; return 0; }',
  '  found=0',
  '  for f in "$sdir"/*.md; do',
  '    [ -f "$f" ] || continue',
  '    found=1',
  '    basename "$f" .md',
  '  done',
  '  [ "$found" -eq 1 ] || echo \'(no peers)\'',
  '}',
  '',
  '# A light repo-health mechanism fact for `wake` (not policy): is the agent clone wedged?',
  'qa_wake_repo_health() {',
  '  gd="$ROOT/repo/.git"',
  '  [ -d "$gd" ] || return 0',
  '  if [ -d "$gd/rebase-merge" ] || [ -d "$gd/rebase-apply" ]; then',
  '    echo "! repo is mid-rebase - resolve before new work (git -C repo rebase --continue / --abort)"',
  '  elif [ -f "$gd/MERGE_HEAD" ]; then',
  '    echo "! repo is mid-merge - resolve before new work (git -C repo merge --continue / --abort)"',
  '  fi',
  '}',
  '',
  '# One name-INDEPENDENT orientation packet. It derives "what is here" from durable state',
  '# (in/received minus in/processed - a `done` parcel is moved out, so received IS the unprocessed',
  '# set), never from the courier line - so an early / lost / duplicated announce is self-healing,',
  '# and `wake` is the safe first move on any wake-up. The granular verbs stay for drill-down.',
  'cmd_wake() {',
  '  qa_wake_repo_health',
  '  echo "-- assignment --"',
  '  if [ -s "$ROOT/assignment.md" ]; then head -n 3 "$ROOT/assignment.md"; else echo "(none set)"; fi',
  '  echo "-- status (your handoff to your successor) --"',
  '  if [ -s "$ROOT/status.md" ]; then head -n 3 "$ROOT/status.md"; else echo "(idle)"; fi',
  '  echo "-- inbox (unprocessed) --"',
  '  cmd_inbox list',
  '  echo "-- peers --"',
  '  cmd_peers',
  '}',
  '',
  'usage() {',
  "  cat <<'EOF'",
  'agent.sh — your Quimby coordination tool (mechanics only; judgment stays in instructions)',
  '',
  '  assignment              show the current assignment',
  '  assignment set -m msg|--file path|-',
  '                          replace the current assignment',
  '  wake                    one orientation packet (repo health, assignment, status, inbox, peers) -',
  '                          name-independent, so run it first on any wake-up (self-heals a raced announce)',
  '  status                  show your current status journal',
  '  status set -m msg|--file path|-',
  '                          replace your status journal',
  '  status append -m msg|--file path|-',
  '                          append to your status journal',
  '  status done [-m msg|--file path|-]',
  '                          append a done summary (default: "done.")',
  '  handoff <recipient> [-m msg] [--attach agent] [--file path] [--draft]',
  '                        author + atomically publish a parcel to a peer',
  '  delegate <recipient> -m msg [--attach agent] [--file path] [--draft]',
  '                        (user-directed) mark a host-promoted directive',
  '  escalate <recipient> [-m msg]   summon your director upward (interrupts; no authority)',
  '  ask <recipient> -m msg          ask a question and get woken by the reply',
  '  reply <recipient> --to <parcel> -m msg   answer a question, waking the asker',
  '                        relay user-directed work to a peer',
  '  publish <recipient>   publish a parcel you drafted with --draft',
  '  inbox [list]          list delivered parcels',
  "  inbox show <parcel>   print a parcel's note and diffstat",
  '  inbox done <parcel>   mark a parcel processed',
  '  attest --command CMD --result pass|fail [--summary S]',
  '                        append a quimby-attest block (atCommit auto-filled from HEAD)',
  '  peers [name]          list peer status mirrors, or read one',
  '',
  "Delivery across the boundary is the host's job (quimby dispatch / merge); this",
  'tool only ever writes your own workspace.',
  'EOF',
  '}',
  '',
  'main() {',
  '  [ $# -gt 0 ] || { usage; exit 0; }',
  '  verb=$1',
  '  shift',
  '  case $verb in',
  '    help|-h|--help) usage; exit 0 ;;',
  '  esac',
  '  ROOT=$(qa_root) || qa_die "not inside an agent workspace (no handoff/ + assignment.md above $PWD)"',
  '  case $verb in',
  '    wake) cmd_wake "$@" ;;',
  '    handoff) cmd_handoff handoff "$@" ;;',
  '    delegate) cmd_handoff delegate "$@" ;;',
  '    escalate) cmd_handoff escalate "$@" ;;',
  '    ask) cmd_handoff ask "$@" ;;',
  '    reply) cmd_handoff reply "$@" ;;',
  '    publish) [ $# -gt 0 ] || qa_die \'publish <recipient>\'; qa_publish "$1" ;;',
  '    inbox) cmd_inbox "$@" ;;',
  '    attest) cmd_attest "$@" ;;',
  '    peers) cmd_peers "$@" ;;',
  '    assignment) cmd_assignment "$@" ;;',
  '    status) cmd_status "$@" ;;',
  '    *) qa_die "unknown command \'$verb\' — run: ./agent.sh help" ;;',
  '  esac',
  '}',
  '',
  'main "$@"',
]

// Windows batch twin. Each JS line escapes `"`→`\"` and `\`→`\\`; backticks are literal. cmd has
// no `${...}`/`\n` semantics, so only backslashes (Windows paths) need doubling. Best-effort and
// unverified on Windows — the .sh above is canonical; this exists only for a Windows-hosted agent.
const CMD_LINES = [
  '@echo off',
  'setlocal enabledelayedexpansion',
  'rem agent.cmd — Windows twin of agent.sh (that file is canonical). Best-effort:',
  'rem remote sandboxes are POSIX, so this only matters for a Windows-hosted agent. If it misbehaves,',
  'rem the CLAUDE.md prose conventions are the fallback. Deps: cmd + git.',
  '',
  'rem The coordination graph, baked in by the host (see the .sh twin). Empty = nothing rendered.',
  'set "QA_GRAPH={{graph}}"',
  'set "QA_ROSTER={{roster}}"',
  'set "QA_ESCALATE={{escalate}}"',
  '',
  'call :find_root',
  'if "%ROOT%"=="" ( echo agent.cmd: not inside an agent workspace 1>&2 & exit /b 1 )',
  '',
  'set "VERB=%~1"',
  'if "%VERB%"=="" goto :usage',
  'shift',
  'if /I "%VERB%"=="help" goto :usage',
  'if /I "%VERB%"=="assignment" goto :assignment',
  'if /I "%VERB%"=="status" goto :status',
  'if /I "%VERB%"=="handoff" ( set "MODE=handoff" & goto :handoff )',
  'if /I "%VERB%"=="delegate" ( set "MODE=delegate" & goto :handoff )',
  'if /I "%VERB%"=="escalate" ( set "MODE=escalate" & goto :handoff )',
  'if /I "%VERB%"=="ask" ( set "MODE=ask" & goto :handoff )',
  'if /I "%VERB%"=="reply" ( set "MODE=reply" & goto :handoff )',
  'if /I "%VERB%"=="publish" goto :publish_cmd',
  'if /I "%VERB%"=="inbox" goto :inbox',
  'if /I "%VERB%"=="attest" goto :attest',
  'if /I "%VERB%"=="peers" goto :peers',
  "echo agent.cmd: unknown command '%VERB%' — run: agent.cmd help 1>&2",
  'exit /b 1',
  '',
  ':find_root',
  'set "ROOT="',
  'set "D=%CD%"',
  ':fr_loop',
  'if exist "%D%\\handoff" if exist "%D%\\assignment.md" ( set "ROOT=%D%" & exit /b 0 )',
  'for %%P in ("%D%\\..") do set "PARENT=%%~fP"',
  'if "%PARENT%"=="%D%" exit /b 0',
  'set "D=%PARENT%"',
  'goto :fr_loop',
  '',
  'rem Exit 0 when %~1 is NOT in the space-separated list %~2 (an empty list is never a mismatch),',
  'rem so the callers above read as `call :not_in_list ... && (complain)`.',
  ':not_in_list',
  'if "%~2"=="" exit /b 0',
  'for %%N in (%~2) do if /I "%%~N"=="%~1" exit /b 1',
  'exit /b 0',
  '',
  ':assignment',
  'set "SUB=%~1"',
  'if "%SUB%"=="" set "SUB=show"',
  'if /I "%SUB%"=="show" ( type "%ROOT%\\assignment.md" & exit /b 0 )',
  'if /I not "%SUB%"=="set" ( echo agent.cmd: assignment: unknown subcommand %SUB% 1>&2 & exit /b 1 )',
  'shift',
  'set "MSG="',
  'set "FILE="',
  ':as_loop',
  'if "%~1"=="" goto :as_done',
  'if /I "%~1"=="-m" ( set "MSG=%~2" & shift & shift & goto :as_loop )',
  'if /I "%~1"=="--message" ( set "MSG=%~2" & shift & shift & goto :as_loop )',
  'if /I "%~1"=="--file" ( set "FILE=%~2" & shift & shift & goto :as_loop )',
  'echo agent.cmd: assignment set: unexpected arg %~1 1>&2 & exit /b 1',
  ':as_done',
  'if not "%FILE%"=="" (',
  '  if "%FILE%"=="-" ( more > "%ROOT%\\assignment.md" ) else ( if not exist "%FILE%" ( echo agent.cmd: assignment set: --file not found: %FILE% 1>&2 & exit /b 1 ) & copy /y "%FILE%" "%ROOT%\\assignment.md" >nul )',
  ') else (',
  '  if "%MSG%"=="" ( echo agent.cmd: assignment set: provide -m or --file 1>&2 & exit /b 1 )',
  '  >"%ROOT%\\assignment.md" echo(%MSG%',
  ')',
  'echo agent.cmd: assignment set',
  'exit /b 0',
  '',
  ':status',
  'set "SUB=%~1"',
  'if "%SUB%"=="" set "SUB=show"',
  'if /I "%SUB%"=="show" ( type "%ROOT%\\status.md" & exit /b 0 )',
  'if /I not "%SUB%"=="set" if /I not "%SUB%"=="append" if /I not "%SUB%"=="done" ( echo agent.cmd: status: unknown subcommand %SUB% 1>&2 & exit /b 1 )',
  'shift',
  'set "MSG="',
  'set "FILE="',
  ':st_loop',
  'if "%~1"=="" goto :st_done',
  'if /I "%~1"=="-m" ( set "MSG=%~2" & shift & shift & goto :st_loop )',
  'if /I "%~1"=="--message" ( set "MSG=%~2" & shift & shift & goto :st_loop )',
  'if /I "%~1"=="--file" ( set "FILE=%~2" & shift & shift & goto :st_loop )',
  'echo agent.cmd: status %SUB%: unexpected arg %~1 1>&2 & exit /b 1',
  ':st_done',
  'if /I "%SUB%"=="done" if "%MSG%"=="" if "%FILE%"=="" set "MSG=done."',
  'if not "%FILE%"=="" (',
  '  if "%FILE%"=="-" ( set "TMP=%TEMP%\\quimby-status-%RANDOM%.tmp" & more > "!TMP!" & set "FILE=!TMP!" )',
  '  if not exist "%FILE%" ( echo agent.cmd: status %SUB%: --file not found: %FILE% 1>&2 & exit /b 1 )',
  '  if /I "%SUB%"=="set" ( copy /y "%FILE%" "%ROOT%\\status.md" >nul ) else ( type "%FILE%" >> "%ROOT%\\status.md" )',
  '  if defined TMP del "!TMP!" >nul 2>nul',
  ') else (',
  '  if "%MSG%"=="" ( echo agent.cmd: status %SUB%: provide -m or --file 1>&2 & exit /b 1 )',
  '  if /I "%SUB%"=="set" ( >"%ROOT%\\status.md" echo(%MSG% ) else ( >>"%ROOT%\\status.md" echo. & >>"%ROOT%\\status.md" echo(%MSG% )',
  ')',
  'echo agent.cmd: status %SUB%',
  'exit /b 0',
  '',
  ':handoff',
  'set "RECIP="',
  'set "MSG="',
  'set "ATTACH="',
  'set "REPLYTO="',
  'set "PUBLISH=1"',
  'set "FILES="',
  ':ho_loop',
  'if "%~1"=="" goto :ho_done',
  'if /I "%~1"=="-m" ( set "MSG=%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--message" ( set "MSG=%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--attach" ( set "ATTACH=%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--to" ( set "REPLYTO=%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--file" ( set FILES=!FILES! "%~2" & shift & shift & goto :ho_loop )',
  'if /I "%~1"=="--draft" ( set "PUBLISH=0" & shift & goto :ho_loop )',
  'if "!RECIP!"=="" ( set "RECIP=%~1" & shift & goto :ho_loop )',
  'echo agent.cmd: handoff: unexpected arg %~1 1>&2 & exit /b 1',
  ':ho_done',
  'if "%RECIP%"=="" ( echo agent.cmd: %MODE%: recipient required 1>&2 & exit /b 1 )',
  // Roster / escalation gate — the .sh twin's qa_in_list, in cmd. An empty list means the host
  // rendered nothing, so it passes rather than blocking a send on missing data.
  'if not "%QA_GRAPH%"=="" call :not_in_list "%RECIP%" "%QA_ROSTER%" && (',
  '  echo agent.cmd: %MODE%: "%RECIP%" is not an agent. 1>&2',
  '  echo   roster: %QA_ROSTER% 1>&2',
  '  exit /b 1',
  ')',
  'if not "%QA_GRAPH%"=="" if not "%ATTACH%"=="" call :not_in_list "%ATTACH%" "%QA_ROSTER%" && (',
  '  echo agent.cmd: %MODE%: --attach "%ATTACH%" is not an agent. 1>&2',
  '  echo   roster: %QA_ROSTER% 1>&2',
  '  exit /b 1',
  ')',
  'if not "%QA_GRAPH%"=="" if "%MODE%"=="escalate" if "%QA_ESCALATE%"=="" (',
  '  echo agent.cmd: escalate: you have no escalation target — everything you send is advisory. 1>&2',
  '  exit /b 1',
  ')',
  'if not "%QA_GRAPH%"=="" if "%MODE%"=="escalate" call :not_in_list "%RECIP%" "%QA_ESCALATE%" && (',
  '  echo agent.cmd: escalate: you may not escalate to "%RECIP%". 1>&2',
  '  echo   permitted: %QA_ESCALATE% 1>&2',
  '  exit /b 1',
  ')',
  'if "%MODE%"=="delegate" if "%MSG%"=="" ( echo agent.cmd: delegate: message required 1>&2 & exit /b 1 )',
  'if "%MODE%"=="reply" if "%REPLYTO%"=="" ( echo agent.cmd: reply: --to ^<parcel^> required 1>&2 & exit /b 1 )',
  // The interrupt-intent tag by verb; the host validates it against the directs graph (§6).
  'set "FM="',
  'if "%MODE%"=="delegate" set "FM=delegated: true"',
  'if "%MODE%"=="escalate" set "FM=escalate: true"',
  'if "%MODE%"=="ask" set "FM=expects-reply: true"',
  'if "%MODE%"=="reply" set "FM=reply-to: %REPLYTO%"',
  'set "DRAFT=%ROOT%\\handoff\\out\\draft\\%RECIP%"',
  'if exist "%DRAFT%" rmdir /s /q "%DRAFT%"',
  'mkdir "%DRAFT%" 2>nul',
  'if not "%FM%%ATTACH%"=="" (',
  '  >"%DRAFT%\\README.md" echo ---',
  '  if not "%FM%"=="" >>"%DRAFT%\\README.md" echo(%FM%',
  '  if not "%ATTACH%"=="" >>"%DRAFT%\\README.md" echo attach: %ATTACH%',
  '  >>"%DRAFT%\\README.md" echo ---',
  '  >>"%DRAFT%\\README.md" echo(%MSG%',
  ') else (',
  '  >"%DRAFT%\\README.md" echo(%MSG%',
  ')',
  'for %%F in (!FILES!) do if not "%%~F"=="" ( if not exist "%%~F" ( echo agent.cmd: handoff: --file not found: %%~F 1>&2 & exit /b 1 ) & copy /y "%%~F" "%DRAFT%\\" >nul )',
  'if "%PUBLISH%"=="0" ( echo agent.cmd: drafted parcel for \'%RECIP%\' & exit /b 0 )',
  'call :do_publish "%RECIP%"',
  'exit /b %ERRORLEVEL%',
  '',
  ':publish_cmd',
  'if "%~1"=="" ( echo agent.cmd: publish ^<recipient^> 1>&2 & exit /b 1 )',
  'call :do_publish "%~1"',
  'exit /b %ERRORLEVEL%',
  '',
  ':do_publish',
  'set "R=%~1"',
  'set "DR=%ROOT%\\handoff\\out\\draft\\%R%"',
  'if not exist "%DR%" ( echo agent.cmd: publish: no draft for \'%R%\' 1>&2 & exit /b 1 )',
  'if not exist "%ROOT%\\handoff\\out\\queued" mkdir "%ROOT%\\handoff\\out\\queued"',
  'set "Q=%ROOT%\\handoff\\out\\queued\\%R%"',
  'if exist "%Q%" rmdir /s /q "%Q%"',
  'move "%DR%" "%Q%" >nul',
  "echo agent.cmd: queued parcel for '%R%'",
  'exit /b 0',
  '',
  ':inbox',
  'set "SUB=%~1"',
  'if "%SUB%"=="" set "SUB=list"',
  'if /I "%SUB%"=="list" (',
  '  goto :inbox_list',
  ')',
  'if /I "%SUB%"=="ls" (',
  '  goto :inbox_list',
  ')',
  'goto :inbox_after_list',
  ':inbox_list',
  '  if not exist "%ROOT%\\handoff\\in\\received" ( echo (inbox empty) & exit /b 0 )',
  '  set "ANY="',
  '  for /d %%D in ("%ROOT%\\handoff\\in\\received\\*") do ( set "ANY=1" & echo %%~nxD )',
  '  if "!ANY!"=="" echo (inbox empty)',
  '  exit /b 0',
  ':inbox_after_list',
  'if /I "%SUB%"=="show" (',
  '  if "%~2"=="" ( echo agent.cmd: inbox show ^<parcel^> 1>&2 & exit /b 1 )',
  '  set "P=%ROOT%\\handoff\\in\\received\\%~2"',
  '  if not exist "!P!" ( echo agent.cmd: inbox: no parcel \'%~2\' 1>&2 & exit /b 1 )',
  '  if exist "!P!\\meta.yaml" findstr /R /C:"^userDirected: *true" "!P!\\meta.yaml" >nul && echo == user-directed work (host-stamped) ==',
  '  if exist "!P!\\README.md" ( echo == note == & type "!P!\\README.md" )',
  '  if exist "!P!\\squashed.diff" ( echo. & echo == diffstat == & git apply --stat "!P!\\squashed.diff" )',
  '  exit /b 0',
  ')',
  'if /I "%SUB%"=="done" (',
  '  if "%~2"=="" ( echo agent.cmd: inbox done ^<parcel^> 1>&2 & exit /b 1 )',
  '  set "P=%ROOT%\\handoff\\in\\received\\%~2"',
  '  if not exist "!P!" ( echo agent.cmd: inbox: no parcel \'%~2\' 1>&2 & exit /b 1 )',
  '  if not exist "%ROOT%\\handoff\\in\\processed" mkdir "%ROOT%\\handoff\\in\\processed"',
  '  set "DEST=%ROOT%\\handoff\\in\\processed\\%~2"',
  '  if exist "!DEST!" rmdir /s /q "!DEST!"',
  '  move "!P!" "!DEST!" >nul',
  "  echo agent.cmd: marked '%~2' processed",
  '  exit /b 0',
  ')',
  "echo agent.cmd: inbox: unknown subcommand '%SUB%' 1>&2 & exit /b 1",
  '',
  ':attest',
  'set "CMD="',
  'set "RESULT="',
  'set "SUMMARY="',
  ':at_loop',
  'if "%~1"=="" goto :at_done',
  'if /I "%~1"=="--command" ( set "CMD=%~2" & shift & shift & goto :at_loop )',
  'if /I "%~1"=="--result" ( set "RESULT=%~2" & shift & shift & goto :at_loop )',
  'if /I "%~1"=="--summary" ( set "SUMMARY=%~2" & shift & shift & goto :at_loop )',
  'echo agent.cmd: attest: unexpected arg %~1 1>&2 & exit /b 1',
  ':at_done',
  'if "%CMD%"=="" ( echo agent.cmd: attest: --command required 1>&2 & exit /b 1 )',
  'if /I not "%RESULT%"=="pass" if /I not "%RESULT%"=="fail" ( echo agent.cmd: attest: --result must be pass or fail 1>&2 & exit /b 1 )',
  'set "HEAD="',
  'for /f "delims=" %%H in (\'git -C "%ROOT%\\repo" rev-parse --short HEAD 2^>nul\') do set "HEAD=%%H"',
  'if "%HEAD%"=="" ( echo agent.cmd: attest: cannot read repo HEAD — commit your work first 1>&2 & exit /b 1 )',
  'set "ST=%ROOT%\\status.md"',
  '>>"%ST%" echo.',
  '>>"%ST%" echo ```quimby-attest',
  '>>"%ST%" echo command: %CMD%',
  '>>"%ST%" echo result: %RESULT%',
  'if not "%SUMMARY%"=="" >>"%ST%" echo summary: %SUMMARY%',
  '>>"%ST%" echo atCommit: %HEAD%',
  '>>"%ST%" echo ```',
  'echo agent.cmd: attested %RESULT% @ %HEAD%',
  'exit /b 0',
  '',
  ':peers',
  'if not "%~1"=="" (',
  '  if not exist "%ROOT%\\status\\%~1.md" ( echo agent.cmd: peers: no status mirror for \'%~1\' 1>&2 & exit /b 1 )',
  '  type "%ROOT%\\status\\%~1.md"',
  '  exit /b 0',
  ')',
  'if not exist "%ROOT%\\status" ( echo (no peers) & exit /b 0 )',
  'set "ANY="',
  'for %%F in ("%ROOT%\\status\\*.md") do ( set "ANY=1" & echo %%~nF )',
  'if "!ANY!"=="" echo (no peers)',
  'exit /b 0',
  '',
  ':usage',
  'echo agent.cmd — your Quimby coordination tool (mechanics only; judgment stays in instructions)',
  'echo.',
  'echo   assignment                                             show the current assignment',
  'echo   assignment set -m msg^|--file path^-                    replace the current assignment',
  'echo   status                                                 show your current status journal',
  'echo   status set^|append^|done -m msg^|--file path^-          update your status journal',
  'echo   handoff ^<recipient^> [-m msg] [--attach agent] [--draft]',
  'echo                                                           author + publish a parcel',
  'echo   delegate ^<recipient^> -m msg [--attach agent] [--draft] relay user-directed work',
  "echo   publish ^<recipient^>                                     publish a --draft'd parcel",
  'echo   inbox [list ^| show ^<p^> ^| done ^<p^>]                    list / read / process parcels',
  'echo   attest --command CMD --result pass^|fail [--summary S]   append a quimby-attest block',
  'echo   peers [name]                                            list peer status, or read one',
  'echo.',
  "echo Delivery across the boundary is the host's job (quimby dispatch / merge).",
  'exit /b 0',
]
