// The advisory pre-commit hook quimby installs into an agent's repo.
//
// It exists because every other signal in this area depends on someone reading something. The
// `agent.sh` footer says the base moved, and the instructions say to apply it before starting an
// arc — but an agent that skips both still commits, and the resulting commit is indistinguishable
// from deliberate work: it reverts a peer's landed change on lines the agent never meant to touch,
// inside a commit named after the agent's own feature. Git cannot catch it downstream, because
// relative to the shared base it IS a deliberate edit, so the boundary merge lands it cleanly.
//
// A git hook is the one place that sees the staged set at the exact moment of the mistake, and it
// cannot be sidestepped by "using git directly" — it is git. That is why this is a hook rather
// than a wrapper around git in `agent.sh`: wrapping git would mean reimplementing an enormous
// surface, every gap teaches the agent to bypass the wrapper, and a control that is trivially
// bypassed while being presented as a control is worse than none.
//
// It WARNS and never blocks (always exits 0). A hook that refuses a commit turns an agent into one
// that fights its tools and reaches for `--no-verify` as a reflex, which would cost more than the
// class of bug it prevents.

/**
 * The `pre-commit` hook for an agent's repo: warns when the commit being made touches files that
 * changed on the delivered base (`quimby/base`) and have not been applied yet — exactly the shape
 * of an accidental revert of a peer's work.
 *
 * POSIX `sh` needing nothing but git and coreutils, the same floor `agent.sh` holds to, so it runs
 * in a sandbox with no Node.
 */
export function renderAgentPreCommitHook(): string {
  return `${HOOK_LINES.join('\n')}\n`
}

const HOOK_LINES = [
  '#!/bin/sh',
  '# Generated by quimby. Advisory only — this never blocks a commit.',
  '#',
  '# Warns when you are committing a file that changed on the delivered base (quimby/base) and that',
  '# you have not applied yet. Committing your older copy of such a file reads downstream as a',
  '# deliberate revert of whoever landed that change, inside a commit named after your own work.',
  'set -u',
  '',
  '# No delivered base yet (a fresh agent, or one that has never synced) — nothing to say.',
  'git rev-parse -q --verify quimby/base >/dev/null 2>&1 || exit 0',
  '',
  '# Compare against the merge base rather than HEAD: what matters is work that has landed on the',
  '# base and that this commit does NOT already contain. Anything applied is not at risk.',
  'mb=$(git merge-base HEAD quimby/base 2>/dev/null) || exit 0',
  'base=$(git rev-parse quimby/base 2>/dev/null) || exit 0',
  '# Already up to date with the delivered base.',
  '[ "$mb" != "$base" ] || exit 0',
  '',
  'landed=$(git diff --name-only "$mb" "$base" 2>/dev/null) || exit 0',
  '[ -n "$landed" ] || exit 0',
  'staged=$(git diff --cached --name-only 2>/dev/null) || exit 0',
  '[ -n "$staged" ] || exit 0',
  '',
  '# The intersection, in portable sh: for each staged path, is it one that moved on the base?',
  '# Both lists are small (a commit, and one base advance), so the nested scan is not worth',
  '# optimising into something that needs a temp file and cleanup inside a hook.',
  'overlap=$(',
  '  printf \'%s\\n\' "$staged" | while IFS= read -r f; do',
  '    [ -n "$f" ] || continue',
  '    printf \'%s\\n\' "$landed" | grep -qxF -- "$f" && printf \'%s\\n\' "$f"',
  '  done',
  ')',
  '[ -n "$overlap" ] || exit 0',
  '',
  'count=$(printf \'%s\\n\' "$overlap" | grep -c .)',
  'echo "" >&2',
  'echo "quimby: WARNING — $count staged file(s) also changed on a base you have not applied:" >&2',
  "printf '%s\\n' \"$overlap\" | head -10 | sed 's/^/            /' >&2",
  '[ "$count" -gt 10 ] && echo "            … and $((count - 10)) more" >&2',
  'echo "" >&2',
  'echo "  Your copy of these predates work that already landed, so committing them reads as a" >&2',
  '# The failure mode named plainly: this is the part that is invisible without being told.',
  'echo "  deliberate revert of whoever landed it — and nothing downstream catches that, because to" >&2',
  'echo "  git it IS a deliberate edit." >&2',
  'echo "" >&2',
  'echo "  Apply the base first: commit your work, then ./agent.sh rebase. Or unstage the paths you" >&2',
  'echo "  did not author (stage your own paths rather than git add -A after a base move)." >&2',
  'echo "" >&2',
  '# Advisory by design: the commit proceeds.',
  'exit 0',
]
