export function renderAgentClaudeMd(opts: { agentName: string; agentId: string }): string {
  const { agentName, agentId } = opts

  const sections = [
    `# Agent Instructions`,
    ``,
    `You are the **${agentName}** agent.`,
    `Your stable agent id is \`${agentId}\` — it never changes, even if you are renamed.`,
    ``,
    `## Workspace Layout`,
    ``,
    `Key paths relative to your agent root:`,
    ``,
    `- \`repo/\` — the source code repository (your main workspace)`,
    `- \`assignment.md\` — your current task (read this first)`,
    `- \`status.md\` — write your current status here`,
    `- \`inbox/\` — parcels and status delivered to you by other agents`,
    `  - \`inbox/<sender>-<hash>/\` — a delivered parcel (\`meta.yaml\` plus an optional \`README.md\` note and/or \`squashed.diff\`)`,
    `  - \`inbox/status/<agent-name>.md\` — latest status from another agent`,
    `  - \`inbox/.done/\` — parcels you have already processed`,
    `- \`outbox/\` — parcels you want delivered to other agents, addressed by recipient`,
    `  - \`outbox/<recipient>/\` — a parcel for that agent; put a \`README.md\` note and any files in it`,
    ``,
    `## How to Work`,
    ``,
    `1. **Read your assignment**: Check \`assignment.md\` for your task`,
    `2. **Work in repo/**: Make changes and commit to the repo as you go`,
    `3. **Update your status**: Write progress to \`status.md\` periodically`,
    `4. **Commit against the baseline**: All your commits are measured against the \`quimby/seed\` tag`,
    ``,
    `## Status Updates`,
    ``,
    `Keep \`status.md\` current. Write a brief summary of:`,
    `- What you're working on`,
    `- Any blockers or questions`,
    `- When you're done, write "done" with a summary`,
    ``,
    `## Incoming Parcels`,
    ``,
    `Check \`inbox/\` for parcels and status from other agents.`,
    `- A parcel in \`inbox/<sender>-<hash>/\` holds a \`meta.yaml\` manifest plus an optional \`README.md\` note and/or \`squashed.diff\` of code`,
    `- When you have processed a parcel, move it to \`inbox/.done/\``,
    `- Status updates in \`inbox/status/<agent>.md\` show other agents' progress`,
    ``,
    `## Handing Work to Other Agents`,
    ``,
    `To send a parcel to another agent, create \`outbox/<recipient>/\` and write a \`README.md\` note (and any files) into it.`,
    `Your committed work is attached automatically; to attach a different agent's diff, add YAML frontmatter to the note:`,
    ``,
    `    ---`,
    `    attach: builder`,
    `    ---`,
    `    Promote builder's work; one nit in auth.ts.`,
    ``,
    `The user runs \`quimby dispatch ${agentName}\` to deliver every queued parcel to its recipient.`,
    ``,
    `## Project Instructions`,
    ``,
    `@repo/CLAUDE.md`,
  ]

  return sections.join('\n') + '\n'
}
